#!/usr/bin/env python3
"""
يبني assets/js/icons.js من أيقونات lucide المستخدمة في القالب فقط.

التشغيل بعد إضافة أيقونة جديدة في أي ملف:
    npm i lucide-static
    python3 tools/build_icons.py --icons node_modules/lucide-static/icons

الطريقة: يجمع كل نص بين علامتي تنصيص بصيغة اسم أيقونة (مثل 'car' أو "map-pin")
من ملفات HTML و JS، ويضم الموجود منها في مجلد lucide. أسماء الأيقونات:
https://lucide.dev/icons
"""
import argparse, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

ap = argparse.ArgumentParser()
ap.add_argument('--icons', required=True, help='path to lucide-static/icons')
args = ap.parse_args()

tokens = set()
for base, dirs, files in os.walk(ROOT):
    dirs[:] = [d for d in dirs if d not in ('node_modules', 'tools', '.git')]
    for f in files:
        if f.endswith(('.html', '.js')) and f != 'icons.js':
            src = open(os.path.join(base, f), encoding='utf8').read()
            tokens.update(re.findall(r"""['"]([a-z][a-z0-9]*(?:-[a-z0-9]+)*)['"]""", src))

out = {}
for n in sorted(tokens):
    p = os.path.join(args.icons, n + '.svg')
    if os.path.exists(p):
        svg = re.sub(r'<!--.*?-->', '', open(p, encoding='utf8').read(), flags=re.S)
        inner = re.search(r'<svg[^>]*>(.*)</svg>', svg, flags=re.S).group(1)
        out[n] = re.sub(r'\s+', ' ', inner).strip()

lines = ['/* Auto-generated by tools/build_icons.py — Lucide icons (ISC license, see LUCIDE-LICENSE.txt). */',
         'window.BT = window.BT || {};', 'BT.ICONS = {']
lines += ["  '%s': '%s'," % (k, v.replace("'", "\\'")) for k, v in sorted(out.items())]
lines += ['};', '']
open(os.path.join(ROOT, 'assets/js/icons.js'), 'w', encoding='utf8').write('\n'.join(lines))
print('icons written:', len(out))
