"""Foundation: org (legal companies, operational branches), identity (company scope), audit, integrations.

Revision ID: 0001_foundation
Revises:
"""

from alembic import op

revision = "0001_foundation"
down_revision = None
branch_labels = None
depends_on = None

SQL = r"""
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE SCHEMA org;
CREATE SCHEMA identity;
CREATE SCHEMA audit;
CREATE SCHEMA integrations;

-- ---------------------------------------------------------------- org
-- Companies are the legal entities: employees are on their papers, vehicles are registered to them.
CREATE TABLE org.companies (
    id               bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT companies_pkey PRIMARY KEY,
    public_id        uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT companies_public_id_key UNIQUE,
    name             jsonb       NOT NULL,                     -- {"ar": "...", "en": "..."}
    trade_name       jsonb,
    cr_number        text        CONSTRAINT companies_cr_number_key UNIQUE,   -- commercial registration
    license_number   text,
    license_expiry   date,
    pam_file_number  text,                                     -- labour file (Public Authority of Manpower)
    phone            text,
    address          text,
    contact_name     text,
    contact_phone    text,
    is_active        boolean     NOT NULL DEFAULT true,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    version          integer     NOT NULL DEFAULT 1
);

-- Branches are operational locations only; they do not limit what anyone can see.
CREATE TABLE org.branches (
    id          bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT branches_pkey PRIMARY KEY,
    public_id   uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT branches_public_id_key UNIQUE,
    name        jsonb       NOT NULL,
    is_default  boolean     NOT NULL DEFAULT false,
    is_active   boolean     NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    version     integer     NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX branches_is_default_idx ON org.branches (is_default) WHERE is_default;
INSERT INTO org.branches (name, is_default) VALUES ('{"ar": "الفرع الرئيسي", "en": "Main branch"}', true);

CREATE TABLE org.settings (
    key         text        CONSTRAINT settings_pkey PRIMARY KEY,
    value       jsonb       NOT NULL,
    version     integer     NOT NULL DEFAULT 1,
    updated_by  bigint,
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- identity
CREATE TABLE identity.users (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT users_pkey PRIMARY KEY,
    public_id             uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT users_public_id_key UNIQUE,
    username              text        NOT NULL,
    full_name             text        NOT NULL,
    phone                 text,
    locale                text,
    password_hash         text        NOT NULL,
    must_change_password  boolean     NOT NULL DEFAULT false,
    totp_secret_enc       text,
    totp_enabled          boolean     NOT NULL DEFAULT false,
    totp_last_step        bigint,
    is_superuser          boolean     NOT NULL DEFAULT false,
    is_active             boolean     NOT NULL DEFAULT true,
    all_companies         boolean     NOT NULL DEFAULT true,
    failed_logins         integer     NOT NULL DEFAULT 0,
    locked_until          timestamptz,
    last_login_at         timestamptz,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    version               integer     NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX users_username_lower_key ON identity.users (lower(username));

CREATE TABLE identity.roles (
    id               bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT roles_pkey PRIMARY KEY,
    code             text        NOT NULL CONSTRAINT roles_code_key UNIQUE,
    name             jsonb       NOT NULL,
    is_system        boolean     NOT NULL DEFAULT false,       -- cannot be edited
    all_permissions  boolean     NOT NULL DEFAULT false,       -- every permission, including ones added later
    created_at       timestamptz NOT NULL DEFAULT now(),
    version          integer     NOT NULL DEFAULT 1
);

CREATE TABLE identity.role_permissions (
    role_id     bigint NOT NULL CONSTRAINT role_permissions_role_id_fkey REFERENCES identity.roles (id) ON DELETE CASCADE,
    permission  text   NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission)
);

CREATE TABLE identity.user_roles (
    user_id  bigint NOT NULL CONSTRAINT user_roles_user_id_fkey REFERENCES identity.users (id) ON DELETE CASCADE,
    role_id  bigint NOT NULL CONSTRAINT user_roles_role_id_fkey REFERENCES identity.roles (id) ON DELETE CASCADE,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id)
);

-- Only used when a user is limited to some companies (all_companies = false).
CREATE TABLE identity.user_companies (
    user_id     bigint NOT NULL CONSTRAINT user_companies_user_id_fkey REFERENCES identity.users (id) ON DELETE CASCADE,
    company_id  bigint NOT NULL CONSTRAINT user_companies_company_id_fkey REFERENCES org.companies (id),
    CONSTRAINT user_companies_pkey PRIMARY KEY (user_id, company_id)
);

CREATE TABLE identity.sessions (
    id            bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT sessions_pkey PRIMARY KEY,
    token_hash    text        NOT NULL CONSTRAINT sessions_token_hash_key UNIQUE,
    user_id       bigint      NOT NULL CONSTRAINT sessions_user_id_fkey REFERENCES identity.users (id) ON DELETE CASCADE,
    mfa_passed    boolean     NOT NULL DEFAULT false,
    csrf_token    text        NOT NULL,
    ip            text,
    user_agent    text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_seen_at  timestamptz NOT NULL DEFAULT now(),
    revoked_at    timestamptz
);
CREATE INDEX sessions_user_id_idx ON identity.sessions (user_id) WHERE revoked_at IS NULL;

-- ---------------------------------------------------------------- audit
CREATE TABLE audit.events (
    id             bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT events_pkey PRIMARY KEY,
    occurred_at    timestamptz NOT NULL DEFAULT now(),
    actor_type     text        NOT NULL CONSTRAINT events_actor_type_check CHECK (actor_type IN ('user', 'system', 'device', 'service')),
    actor_user_id  bigint,
    action         text        NOT NULL,
    entity_type    text        NOT NULL,
    entity_id      text,
    company_id     bigint,
    before         jsonb,
    after          jsonb,
    ip             text,
    request_id     text
);
CREATE INDEX events_entity_idx ON audit.events (entity_type, entity_id, id);
CREATE INDEX events_occurred_at_idx ON audit.events (occurred_at);

-- The audit trail is append-only for everyone, owner included.
CREATE FUNCTION audit.forbid_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit events are append-only';
END $$;
CREATE TRIGGER events_append_only BEFORE UPDATE OR DELETE ON audit.events
    FOR EACH ROW EXECUTE FUNCTION audit.forbid_change();

-- ---------------------------------------------------------------- integrations
CREATE TABLE integrations.outbox (
    id             bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT outbox_pkey PRIMARY KEY,
    event_id       uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT outbox_event_id_key UNIQUE,
    event_type     text        NOT NULL,
    event_version  smallint    NOT NULL DEFAULT 1,
    aggregate_id   uuid        NOT NULL,
    payload        jsonb       NOT NULL,
    occurred_at    timestamptz NOT NULL DEFAULT now(),
    published_at   timestamptz
);
CREATE INDEX outbox_unpublished_idx ON integrations.outbox (id) WHERE published_at IS NULL;

CREATE TABLE integrations.subscriptions (
    id           bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT subscriptions_pkey PRIMARY KEY,
    name         text    NOT NULL CONSTRAINT subscriptions_name_key UNIQUE,
    target_url   text,
    event_types  text[]  NOT NULL,
    active       boolean NOT NULL DEFAULT true
);

CREATE TABLE integrations.deliveries (
    event_id         uuid        NOT NULL CONSTRAINT deliveries_event_id_fkey REFERENCES integrations.outbox (event_id),
    subscription_id  bigint      NOT NULL CONSTRAINT deliveries_subscription_id_fkey REFERENCES integrations.subscriptions (id),
    status           text        NOT NULL DEFAULT 'pending' CONSTRAINT deliveries_status_check CHECK (status IN ('pending', 'delivered', 'dead')),
    attempts         integer     NOT NULL DEFAULT 0,
    next_attempt_at  timestamptz NOT NULL DEFAULT now(),
    last_error       text,
    delivered_at     timestamptz,
    CONSTRAINT deliveries_pkey PRIMARY KEY (event_id, subscription_id)
);
CREATE INDEX deliveries_next_attempt_at_idx ON integrations.deliveries (next_attempt_at) WHERE status = 'pending';

CREATE TABLE integrations.processed_events (
    consumer      text        NOT NULL,
    event_id      uuid        NOT NULL,
    processed_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT processed_events_pkey PRIMARY KEY (consumer, event_id)
);

-- ---------------------------------------------------------------- least-privilege application role
-- Every migration ends with SELECT public.fleet_apply_grants(). Does nothing if the role does not exist yet;
-- schemas that do not exist yet are skipped, so later modules only need to call it again.
CREATE FUNCTION public.fleet_apply_grants() RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    s text;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fleet_app') THEN
        RETURN;
    END IF;
    FOR s IN SELECT nspname FROM pg_namespace
             WHERE nspname = ANY (ARRAY['org', 'identity', 'audit', 'integrations', 'i18n', 'people', 'fleet',
                                        'tracking', 'daily_ops', 'cash', 'maintenance', 'accidents', 'payroll',
                                        'finance', 'approvals', 'notifications', 'reports'])
    LOOP
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO fleet_app', s);
        EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO fleet_app', s);
        IF s = 'audit' THEN
            EXECUTE 'GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA audit TO fleet_app';
        ELSE
            EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO fleet_app', s);
        END IF;
    END LOOP;
    EXECUTE 'ALTER ROLE fleet_app SET statement_timeout = ''30s''';
END $$;

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    # plain DBAPI execute: multi-statement DDL, no bind-parameter parsing of plpgsql '%I' / ':'
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
