"""M1: files, people, documents, vehicles, custody, odometer, driver devices, tracking, alerts.

Revision ID: 0004_m1_fleet
Revises: 0003_role_templates
"""

from alembic import op

revision = "0004_m1_fleet"
down_revision = "0003_role_templates"
branch_labels = None
depends_on = None

SQL = r"""
CREATE SCHEMA files;
CREATE SCHEMA people;
CREATE SCHEMA documents;
CREATE SCHEMA fleet;
CREATE SCHEMA tracking;
CREATE SCHEMA notifications;

-- ---------------------------------------------------------------- files
-- Immutable, named by their sha256: a record always points to a file that exists (backup consistency, spec 15.4).
CREATE TABLE files.files (
    sha256              text        CONSTRAINT files_pkey PRIMARY KEY CONSTRAINT files_sha256_check CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    size_bytes          integer     NOT NULL CONSTRAINT files_size_bytes_check CHECK (size_bytes > 0),
    content_type        text        NOT NULL CONSTRAINT files_content_type_check
                                    CHECK (content_type IN ('image/jpeg', 'image/png', 'application/pdf')),
    source              text        NOT NULL CONSTRAINT files_source_check CHECK (source IN ('camera', 'upload')),
    uploaded_by_user    bigint,
    uploaded_by_device  bigint,
    uploaded_at         timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------- people
CREATE TABLE people.employment_statuses (
    code         text    CONSTRAINT employment_statuses_pkey PRIMARY KEY
                         CONSTRAINT employment_statuses_code_check CHECK (code ~ '^[a-z][a-z0-9_]{1,30}$'),
    name         jsonb   NOT NULL,
    is_working   boolean NOT NULL DEFAULT true,       -- counts as on the job
    is_terminal  boolean NOT NULL DEFAULT false,      -- resignation / end of service: driver app access is disabled
    is_active    boolean NOT NULL DEFAULT true,
    sort_order   integer NOT NULL DEFAULT 100
);
INSERT INTO people.employment_statuses (code, name, is_working, is_terminal, sort_order) VALUES
    ('under_visa', '{"ar": "تحت إجراء الفيزا", "en": "Visa in process"}', false, false, 10),
    ('active', '{"ar": "على رأس العمل", "en": "On the job"}', true, false, 20),
    ('on_leave', '{"ar": "في إجازة", "en": "On leave"}', false, false, 30),
    ('suspended', '{"ar": "موقوف عن العمل", "en": "Suspended"}', false, false, 40),
    ('resigned', '{"ar": "مستقيل", "en": "Resigned"}', false, true, 50),
    ('terminated', '{"ar": "منتهي الخدمة", "en": "Service ended"}', false, true, 60);

CREATE TABLE people.employees (
    id               bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT employees_pkey PRIMARY KEY,
    public_id        uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT employees_public_id_key UNIQUE,
    employee_number  text          NOT NULL CONSTRAINT employees_employee_number_key UNIQUE,
    name             jsonb         NOT NULL,
    civil_id         text          CONSTRAINT employees_civil_id_key UNIQUE
                                   CONSTRAINT employees_civil_id_check CHECK (civil_id ~ '^[0-9]{12}$'),
    nationality      text,
    company_id       bigint        NOT NULL CONSTRAINT employees_company_id_fkey REFERENCES org.companies (id),
    branch_id        bigint        NOT NULL CONSTRAINT employees_branch_id_fkey REFERENCES org.branches (id),
    department       text,
    job_title        text,
    is_driver        boolean       NOT NULL DEFAULT false,
    phone            text          CONSTRAINT employees_phone_check CHECK (phone ~ '^\+[1-9][0-9]{7,14}$'),
    hire_date        date,
    basic_salary     numeric(12,3) CONSTRAINT employees_basic_salary_check CHECK (basic_salary >= 0),
    iban             text,
    status_code      text          NOT NULL CONSTRAINT employees_status_code_fkey REFERENCES people.employment_statuses (code),
    app_access       text          NOT NULL DEFAULT 'none' CONSTRAINT employees_app_access_check
                                   CHECK (app_access IN ('none', 'active', 'suspended', 'disabled')),
    created_at       timestamptz   NOT NULL DEFAULT now(),
    updated_at       timestamptz   NOT NULL DEFAULT now(),
    version          integer       NOT NULL DEFAULT 1,
    CONSTRAINT employees_driver_phone_check CHECK (NOT is_driver OR phone IS NOT NULL)
);
-- one person per phone number: the OTP must reach exactly one driver
CREATE UNIQUE INDEX employees_phone_idx ON people.employees (phone) WHERE phone IS NOT NULL;
CREATE INDEX employees_company_id_idx ON people.employees (company_id);

CREATE TABLE people.status_history (
    id           bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT status_history_pkey PRIMARY KEY,
    employee_id  bigint      NOT NULL CONSTRAINT status_history_employee_id_fkey REFERENCES people.employees (id),
    status_code  text        NOT NULL CONSTRAINT status_history_status_code_fkey REFERENCES people.employment_statuses (code),
    changed_at   timestamptz NOT NULL DEFAULT now(),
    changed_by   bigint,
    note         text
);
CREATE INDEX status_history_employee_id_idx ON people.status_history (employee_id, id);

-- Matching keys for a future HR integration (spec 14.2).
CREATE TABLE people.external_refs (
    system       text   NOT NULL,
    external_id  text   NOT NULL,
    employee_id  bigint NOT NULL CONSTRAINT external_refs_employee_id_fkey REFERENCES people.employees (id),
    CONSTRAINT external_refs_pkey PRIMARY KEY (system, external_id),
    CONSTRAINT external_refs_system_employee_key UNIQUE (system, employee_id)
);

-- ---------------------------------------------------------------- fleet
CREATE TABLE fleet.vehicles (
    id                bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT vehicles_pkey PRIMARY KEY,
    public_id         uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT vehicles_public_id_key UNIQUE,
    plate_number      text        NOT NULL,
    make              text,
    model             text,
    year              smallint    CONSTRAINT vehicles_year_check CHECK (year BETWEEN 1980 AND 2100),
    color             text,
    vin               text        CONSTRAINT vehicles_vin_key UNIQUE,
    company_id        bigint      NOT NULL CONSTRAINT vehicles_company_id_fkey REFERENCES org.companies (id),
    branch_id         bigint      NOT NULL CONSTRAINT vehicles_branch_id_fkey REFERENCES org.branches (id),
    status            text        NOT NULL DEFAULT 'available' CONSTRAINT vehicles_status_check
                                  CHECK (status IN ('available', 'assigned', 'maintenance', 'accident', 'inactive')),
    last_odometer_km  integer,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    version           integer     NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX vehicles_plate_number_idx ON fleet.vehicles (upper(regexp_replace(plate_number, '\s', '', 'g')));
CREATE INDEX vehicles_company_id_idx ON fleet.vehicles (company_id);

-- Custody periods never overlap, per vehicle or per driver: "who had the vehicle at time T" has one answer,
-- and every GPS point belongs to exactly one custody (spec 6.2).
CREATE TABLE fleet.custodies (
    id              bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT custodies_pkey PRIMARY KEY,
    public_id       uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT custodies_public_id_key UNIQUE,
    vehicle_id      bigint      NOT NULL CONSTRAINT custodies_vehicle_id_fkey REFERENCES fleet.vehicles (id),
    driver_id       bigint      NOT NULL CONSTRAINT custodies_driver_id_fkey REFERENCES people.employees (id),
    company_id      bigint      NOT NULL,                     -- the vehicle's company, for scope
    started_at      timestamptz NOT NULL,
    ended_at        timestamptz,
    kind            text        NOT NULL DEFAULT 'normal' CONSTRAINT custodies_kind_check CHECK (kind IN ('normal', 'emergency')),
    reason          text,
    needs_review    boolean     NOT NULL DEFAULT false,
    handed_over_by  bigint      NOT NULL,
    returned_by     bigint,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT custodies_period_check CHECK (ended_at IS NULL OR ended_at > started_at),
    CONSTRAINT custodies_reason_check CHECK (kind <> 'emergency' OR reason IS NOT NULL),
    CONSTRAINT custodies_vehicle_overlap EXCLUDE USING gist (vehicle_id WITH =, tstzrange(started_at, ended_at) WITH &&),
    CONSTRAINT custodies_driver_overlap EXCLUDE USING gist (driver_id WITH =, tstzrange(started_at, ended_at) WITH &&)
);

CREATE TABLE fleet.odometer_readings (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT odometer_readings_pkey PRIMARY KEY,
    public_id          uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT odometer_readings_public_id_key UNIQUE,
    vehicle_id         bigint      NOT NULL CONSTRAINT odometer_readings_vehicle_id_fkey REFERENCES fleet.vehicles (id),
    custody_id         bigint      CONSTRAINT odometer_readings_custody_id_fkey REFERENCES fleet.custodies (id),
    driver_id          bigint,
    kind               text        NOT NULL CONSTRAINT odometer_readings_kind_check
                                   CHECK (kind IN ('handover', 'return', 'start_day', 'end_day')),
    value_km           integer     NOT NULL CONSTRAINT odometer_readings_value_km_check CHECK (value_km >= 0),
    corrected_km       integer     CONSTRAINT odometer_readings_corrected_km_check CHECK (corrected_km >= 0),
    photo_sha256       text        NOT NULL CONSTRAINT odometer_readings_photo_sha256_fkey REFERENCES files.files (sha256),
    recorded_at        timestamptz NOT NULL,
    business_date      date        NOT NULL,                 -- Kuwait date of recorded_at
    received_at        timestamptz NOT NULL DEFAULT now(),
    lat                double precision,
    lng                double precision,
    flags              text[]      NOT NULL DEFAULT '{}',
    review_status      text        NOT NULL DEFAULT 'ok' CONSTRAINT odometer_readings_review_status_check
                                   CHECK (review_status IN ('ok', 'pending', 'reviewed')),
    reviewed_by        bigint,
    reviewed_at        timestamptz,
    review_reason      text,
    created_by_user    bigint,
    created_by_device  bigint,
    CONSTRAINT odometer_readings_correction_check CHECK (corrected_km IS NULL OR review_reason IS NOT NULL)
);
CREATE INDEX odometer_readings_vehicle_id_idx ON fleet.odometer_readings (vehicle_id, recorded_at);
-- one start-of-day reading per custody and day
CREATE UNIQUE INDEX odometer_readings_start_day_idx ON fleet.odometer_readings (custody_id, business_date)
    WHERE kind = 'start_day';

-- ---------------------------------------------------------------- documents
CREATE TABLE documents.document_types (
    code             text    CONSTRAINT document_types_pkey PRIMARY KEY,
    name             jsonb   NOT NULL,
    applies_to       text    NOT NULL CONSTRAINT document_types_applies_to_check CHECK (applies_to IN ('employee', 'vehicle', 'company')),
    requires_expiry  boolean NOT NULL DEFAULT true,
    is_active        boolean NOT NULL DEFAULT true,
    sort_order       integer NOT NULL DEFAULT 100
);
INSERT INTO documents.document_types (code, name, applies_to, requires_expiry, sort_order) VALUES
    ('residence', '{"ar": "الإقامة", "en": "Residence permit"}', 'employee', true, 10),
    ('passport', '{"ar": "جواز السفر", "en": "Passport"}', 'employee', true, 20),
    ('civil_id', '{"ar": "البطاقة المدنية", "en": "Civil ID card"}', 'employee', true, 30),
    ('driving_license', '{"ar": "رخصة القيادة", "en": "Driving licence"}', 'employee', true, 40),
    ('contract', '{"ar": "عقد العمل", "en": "Employment contract"}', 'employee', false, 50),
    ('registration', '{"ar": "الاستمارة", "en": "Vehicle registration"}', 'vehicle', true, 60),
    ('insurance', '{"ar": "التأمين", "en": "Insurance"}', 'vehicle', true, 70),
    ('commercial_license', '{"ar": "الترخيص التجاري", "en": "Commercial licence"}', 'company', true, 80);

CREATE TABLE documents.documents (
    id            bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT documents_pkey PRIMARY KEY,
    public_id     uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT documents_public_id_key UNIQUE,
    type_code     text        NOT NULL CONSTRAINT documents_type_code_fkey REFERENCES documents.document_types (code),
    owner_type    text        NOT NULL CONSTRAINT documents_owner_type_check CHECK (owner_type IN ('employee', 'vehicle', 'company')),
    owner_id      bigint      NOT NULL,
    company_id    bigint      NOT NULL,                       -- the owner's company, for scope
    number        text,
    issue_date    date,
    expiry_date   date,
    file_sha256   text        CONSTRAINT documents_file_sha256_fkey REFERENCES files.files (sha256),
    notes         text,
    is_current    boolean     NOT NULL DEFAULT true,          -- a renewal keeps the old document as history
    created_by    bigint,
    created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX documents_current_idx ON documents.documents (type_code, owner_type, owner_id) WHERE is_current;
CREATE INDEX documents_expiry_date_idx ON documents.documents (expiry_date) WHERE is_current;

-- ---------------------------------------------------------------- identity: driver devices
CREATE TABLE identity.devices (
    id              bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT devices_pkey PRIMARY KEY,
    public_id       uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT devices_public_id_key UNIQUE,
    employee_id     bigint      NOT NULL CONSTRAINT devices_employee_id_fkey REFERENCES people.employees (id),
    device_uid      text        NOT NULL,
    platform        text,
    model           text,
    app_version     text,
    bound_at        timestamptz NOT NULL DEFAULT now(),
    last_seen_at    timestamptz,
    revoked_at      timestamptz,
    revoked_reason  text
);
-- one active device per driver; binding a new one revokes the old one in the same transaction
CREATE UNIQUE INDEX devices_employee_id_idx ON identity.devices (employee_id) WHERE revoked_at IS NULL;

CREATE TABLE identity.device_tokens (
    id          bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT device_tokens_pkey PRIMARY KEY,
    device_id   bigint      NOT NULL CONSTRAINT device_tokens_device_id_fkey REFERENCES identity.devices (id),
    token_hash  text        NOT NULL CONSTRAINT device_tokens_token_hash_key UNIQUE,
    kind        text        NOT NULL CONSTRAINT device_tokens_kind_check CHECK (kind IN ('access', 'refresh')),
    family      uuid        NOT NULL,                     -- a reused refresh token revokes its whole family
    expires_at  timestamptz NOT NULL,
    revoked_at  timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX device_tokens_family_idx ON identity.device_tokens (family);

CREATE TABLE identity.otp_challenges (
    id           bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT otp_challenges_pkey PRIMARY KEY,
    phone        text        NOT NULL,
    employee_id  bigint,                                  -- NULL for unknown phones: rate-limited the same way
    device_uid   text        NOT NULL,
    code_hash    text,
    attempts     integer     NOT NULL DEFAULT 0,
    created_at   timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL,
    consumed_at  timestamptz,
    ip           text
);
CREATE INDEX otp_challenges_phone_idx ON identity.otp_challenges (phone, created_at);

CREATE TABLE identity.device_status (
    device_id                     bigint      CONSTRAINT device_status_pkey PRIMARY KEY
                                              CONSTRAINT device_status_device_id_fkey REFERENCES identity.devices (id),
    reported_at                   timestamptz NOT NULL DEFAULT now(),
    location_permission           text,       -- always / while_in_use / denied
    gps_enabled                   boolean,
    battery_optimization_ignored  boolean,
    tracking_service_running      boolean,
    battery_level                 smallint,
    queue_size                    integer,
    last_upload_at                timestamptz,
    app_version                   text,
    payload                       jsonb       NOT NULL DEFAULT '{}'
);

-- ---------------------------------------------------------------- tracking (spec, appendix D: tested)
CREATE TABLE tracking.positions (
    vehicle_id      bigint           NOT NULL,
    recorded_at     timestamptz      NOT NULL,            -- device time, corrected for clock offset
    received_at     timestamptz      NOT NULL DEFAULT now(),
    custody_id      bigint           NOT NULL,
    driver_id       bigint           NOT NULL,
    device_id       bigint           NOT NULL,
    device_seq      bigint           NOT NULL,
    device_offset_s integer          NOT NULL DEFAULT 0,
    lat             double precision NOT NULL CONSTRAINT positions_lat_check CHECK (lat BETWEEN -90 AND 90),
    lng             double precision NOT NULL CONSTRAINT positions_lng_check CHECK (lng BETWEEN -180 AND 180),
    accuracy_m      real,
    speed_kmh       real,
    heading         smallint,
    CONSTRAINT positions_pkey PRIMARY KEY (vehicle_id, recorded_at)
) PARTITION BY RANGE (recorded_at);

-- monthly partition on Kuwait-time boundaries; a daily job calls it for the next two months
-- SECURITY DEFINER: only the owner may add partitions; the app role calls these two functions and nothing more.
CREATE FUNCTION tracking.ensure_month_partition(p_month date)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog AS $$
DECLARE
    v_start timestamptz := date_trunc('month', p_month::timestamp) AT TIME ZONE 'Asia/Kuwait';
    v_end   timestamptz := (date_trunc('month', p_month::timestamp) + interval '1 month') AT TIME ZONE 'Asia/Kuwait';
    v_name  text        := format('positions_%s', to_char(p_month, 'YYYY_MM'));
BEGIN
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS tracking.%I PARTITION OF tracking.positions FOR VALUES FROM (%L) TO (%L)',
        v_name, v_start, v_end);
END $$;
-- drops whole monthly partitions older than p_keep_months (after their daily summaries exist)
CREATE FUNCTION tracking.drop_partitions_before(p_month date)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog AS $$
DECLARE
    r record;
    dropped integer := 0;
BEGIN
    FOR r IN SELECT c.relname FROM pg_inherits i JOIN pg_class c ON c.oid = i.inhrelid
             WHERE i.inhparent = 'tracking.positions'::regclass
               AND c.relname ~ '^positions_[0-9]{4}_[0-9]{2}$'
               AND c.relname < format('positions_%s', to_char(p_month, 'YYYY_MM'))
    LOOP
        EXECUTE format('DROP TABLE tracking.%I', r.relname);
        dropped := dropped + 1;
    END LOOP;
    RETURN dropped;
END $$;
REVOKE ALL ON FUNCTION tracking.ensure_month_partition(date), tracking.drop_partitions_before(date) FROM PUBLIC;

SELECT tracking.ensure_month_partition((now() AT TIME ZONE 'Asia/Kuwait')::date);
SELECT tracking.ensure_month_partition(((now() AT TIME ZONE 'Asia/Kuwait') + interval '1 month')::date);

CREATE TABLE tracking.last_positions (
    vehicle_id             bigint           CONSTRAINT last_positions_pkey PRIMARY KEY,
    recorded_at            timestamptz      NOT NULL,
    custody_id             bigint           NOT NULL,
    driver_id              bigint           NOT NULL,
    lat                    double precision NOT NULL,
    lng                    double precision NOT NULL,
    speed_kmh              real,
    heading                smallint,
    signal_lost_alerted_at timestamptz
);

-- Mock locations are rejected (BRD) and kept only as security events.
CREATE TABLE tracking.mock_events (
    device_id    bigint      NOT NULL,
    recorded_at  timestamptz NOT NULL,
    driver_id    bigint      NOT NULL,
    custody_id   bigint,
    received_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT mock_events_pkey PRIMARY KEY (device_id, recorded_at)
);

-- Every seq not stored as its own row is logged for 30 days: stored + logged must be an unbroken sequence.
CREATE TABLE tracking.rejected_points (
    device_id    bigint      NOT NULL,
    device_seq   bigint      NOT NULL,
    reason       text        NOT NULL,
    received_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT rejected_points_pkey PRIMARY KEY (device_id, device_seq)
);

-- ---------------------------------------------------------------- notifications: in-app alerts
CREATE TABLE notifications.alerts (
    id               bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT alerts_pkey PRIMARY KEY,
    public_id        uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT alerts_public_id_key UNIQUE,
    kind             text        NOT NULL,                -- message: translations "alerts.<kind>"
    severity         text        NOT NULL CONSTRAINT alerts_severity_check CHECK (severity IN ('info', 'warning', 'critical')),
    permission       text        NOT NULL,                -- only users holding it see the alert
    company_id       bigint,                              -- and only within their company scope
    entity_type      text,
    entity_id        text,
    params           jsonb       NOT NULL DEFAULT '{}',
    dedupe_key       text,
    created_at       timestamptz NOT NULL DEFAULT now(),
    acknowledged_at  timestamptz,
    acknowledged_by  bigint
);
-- one open alert per situation
CREATE UNIQUE INDEX alerts_dedupe_key_idx ON notifications.alerts (dedupe_key) WHERE acknowledged_at IS NULL;
CREATE INDEX alerts_open_idx ON notifications.alerts (created_at) WHERE acknowledged_at IS NULL;

-- ---------------------------------------------------------------- grants for the new schemas
CREATE OR REPLACE FUNCTION public.fleet_apply_grants() RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    s text;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fleet_app') THEN
        RETURN;
    END IF;
    FOR s IN SELECT nspname FROM pg_namespace
             WHERE nspname = ANY (ARRAY['org', 'identity', 'audit', 'integrations', 'i18n', 'files', 'people',
                                        'documents', 'fleet', 'tracking', 'daily_ops', 'cash', 'maintenance',
                                        'accidents', 'payroll', 'finance', 'approvals', 'notifications', 'reports'])
    LOOP
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO fleet_app', s);
        EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO fleet_app', s);
        IF s = 'audit' THEN
            EXECUTE 'GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA audit TO fleet_app';
        ELSE
            EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO fleet_app', s);
        END IF;
    END LOOP;
    IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'tracking') THEN
        EXECUTE 'GRANT EXECUTE ON FUNCTION tracking.ensure_month_partition(date), '
                'tracking.drop_partitions_before(date) TO fleet_app';
    END IF;
    EXECUTE 'ALTER ROLE fleet_app SET statement_timeout = ''30s''';
END $$;

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
