"""Driver activation links: the supervisor sends a one-time link to the driver's registered WhatsApp number, and
opening it binds the phone without an OTP.

Revision ID: 0005_activation_links
Revises: 0004_m1_fleet
"""

from alembic import op

revision = "0005_activation_links"
down_revision = "0004_m1_fleet"
branch_labels = None
depends_on = None

SQL = r"""
CREATE TABLE identity.activation_links (
    id              bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT activation_links_pkey PRIMARY KEY,
    employee_id     bigint      NOT NULL CONSTRAINT activation_links_employee_id_fkey REFERENCES people.employees (id),
    token_hash      text        NOT NULL CONSTRAINT activation_links_token_hash_key UNIQUE,
    channel         text        NOT NULL CONSTRAINT activation_links_channel_check CHECK (channel IN ('whatsapp', 'manual')),
    created_by      bigint      NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    expires_at      timestamptz NOT NULL,
    used_at         timestamptz,
    used_device_id  bigint      CONSTRAINT activation_links_used_device_id_fkey REFERENCES identity.devices (id),
    revoked_at      timestamptz
);
CREATE INDEX activation_links_employee_id_idx ON identity.activation_links (employee_id, created_at);

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
