"""Driver self-registration: after the activation link, the driver sends his data, documents, the vehicle he holds
and its photos; a reviewer approves (everything is applied at once) or rejects with a reason.

Revision ID: 0006_onboarding
Revises: 0005_activation_links
"""

from alembic import op

revision = "0006_onboarding"
down_revision = "0005_activation_links"
branch_labels = None
depends_on = None

SQL = r"""
CREATE SCHEMA onboarding;

CREATE TABLE onboarding.submissions (
    id            bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT submissions_pkey PRIMARY KEY,
    public_id     uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT submissions_public_id_key UNIQUE,
    employee_id   bigint      NOT NULL CONSTRAINT submissions_employee_id_fkey REFERENCES people.employees (id)
                              CONSTRAINT submissions_employee_id_key UNIQUE,
    company_id    bigint      NOT NULL,                   -- the employee's company, for scope
    status        text        NOT NULL DEFAULT 'draft' CONSTRAINT submissions_status_check
                              CHECK (status IN ('draft', 'submitted', 'approved', 'rejected')),
    data          jsonb       NOT NULL DEFAULT '{}',     -- what the driver entered (validated by the application)
    submitted_at  timestamptz,
    reviewed_at   timestamptz,
    reviewed_by   bigint,
    review_note   text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    version       integer     NOT NULL DEFAULT 1
);
CREATE INDEX submissions_status_idx ON onboarding.submissions (status, submitted_at);

-- condition photos of the vehicle at handover and return (front, back, sides, interior, close-ups)
CREATE TABLE fleet.custody_photos (
    custody_id   bigint NOT NULL CONSTRAINT custody_photos_custody_id_fkey REFERENCES fleet.custodies (id),
    stage        text   NOT NULL CONSTRAINT custody_photos_stage_check CHECK (stage IN ('handover', 'return')),
    position     text   NOT NULL CONSTRAINT custody_photos_position_check
                        CHECK (position IN ('front', 'back', 'left', 'right', 'interior', 'other')),
    file_sha256  text   NOT NULL CONSTRAINT custody_photos_file_sha256_fkey REFERENCES files.files (sha256),
    CONSTRAINT custody_photos_pkey PRIMARY KEY (custody_id, stage, file_sha256)
);

-- most cards have two sides (civil ID, driving licence)
ALTER TABLE documents.documents
    ADD COLUMN file_back_sha256 text CONSTRAINT documents_file_back_sha256_fkey REFERENCES files.files (sha256);

-- the new permission employees.onboarding, given to the matching role templates
INSERT INTO identity.role_permissions (role_id, permission)
SELECT id, 'employees.onboarding' FROM identity.roles WHERE code IN ('hr', 'supervisor')
ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION public.fleet_apply_grants() RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    s text;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fleet_app') THEN
        RETURN;
    END IF;
    FOR s IN SELECT nspname FROM pg_namespace
             WHERE nspname = ANY (ARRAY['org', 'identity', 'audit', 'integrations', 'i18n', 'files', 'people',
                                        'documents', 'fleet', 'tracking', 'onboarding', 'daily_ops', 'cash',
                                        'maintenance', 'accidents', 'payroll', 'finance', 'approvals',
                                        'notifications', 'reports'])
    LOOP
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO fleet_app', s);
        EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO fleet_app', s);
        IF s = 'audit' THEN
            EXECUTE 'GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA audit TO fleet_app';
        ELSE
            EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO fleet_app', s);
        END IF;
    END LOOP;
    IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'tracking') THEN
        EXECUTE 'GRANT EXECUTE ON FUNCTION tracking.ensure_month_partition(date), '
                'tracking.drop_partitions_before(date) TO fleet_app';
    END IF;
    EXECUTE 'ALTER ROLE fleet_app SET statement_timeout = ''30s''';
END $$;

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
