"""Queue of activation links sent in bulk: one WhatsApp message at a time, spaced out, within daily limits.

Revision ID: 0007_link_queue
Revises: 0006_onboarding
"""

from alembic import op

revision = "0007_link_queue"
down_revision = "0006_onboarding"
branch_labels = None
depends_on = None

SQL = r"""
CREATE TABLE identity.link_queue (
    id            bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT link_queue_pkey PRIMARY KEY,
    public_id     uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT link_queue_public_id_key UNIQUE,
    employee_id   bigint      NOT NULL CONSTRAINT link_queue_employee_id_fkey REFERENCES people.employees (id),
    company_id    bigint      NOT NULL,
    onboarding    boolean     NOT NULL,
    requested_by  bigint      NOT NULL,
    requested_at  timestamptz NOT NULL DEFAULT now(),
    status        text        NOT NULL DEFAULT 'queued' CONSTRAINT link_queue_status_check
                              CHECK (status IN ('queued', 'sent', 'failed', 'cancelled')),
    attempts      integer     NOT NULL DEFAULT 0,
    last_attempt_at timestamptz,
    sent_at       timestamptz,
    error         text
);
-- one waiting message per driver
CREATE UNIQUE INDEX link_queue_employee_id_idx ON identity.link_queue (employee_id) WHERE status = 'queued';
CREATE INDEX link_queue_status_idx ON identity.link_queue (status, id);

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
