"""M2: the cash ledger (spec, appendix E: tested) and the drivers' daily reports.

Double entry, debit positive and credit negative everywhere; a driver account with a positive balance means the
driver holds company cash. Journals are append-only; the only change allowed is pending -> posted / rejected, and
every guard is enforced by the database itself. Differences from the spec text: a journal may be created by a
driver's device (daily report) instead of a user, an "opening" kind and account for the go-live balances, and
foreign keys to employees and branches.

Revision ID: 0008_cash_daily_ops
Revises: 0007_link_queue
"""

from alembic import op

revision = "0008_cash_daily_ops"
down_revision = "0007_link_queue"
branch_labels = None
depends_on = None

SQL = r"""
CREATE SCHEMA cash;
CREATE SCHEMA daily_ops;

CREATE TABLE cash.accounts (
    id         bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT accounts_pkey PRIMARY KEY,
    kind       text   NOT NULL CONSTRAINT accounts_kind_check
                      CHECK (kind IN ('driver', 'treasury', 'bank', 'cod_clearing', 'adjustments',
                                      'payroll_recovery', 'writeoff', 'opening')),
    driver_id  bigint CONSTRAINT accounts_driver_id_fkey REFERENCES people.employees (id),
    branch_id  bigint CONSTRAINT accounts_branch_id_fkey REFERENCES org.branches (id),
    closed_at  timestamptz,
    CONSTRAINT accounts_driver_check CHECK ((kind = 'driver') = (driver_id IS NOT NULL)),
    CONSTRAINT accounts_kind_key UNIQUE NULLS NOT DISTINCT (kind, driver_id, branch_id)
);

CREATE TABLE cash.journals (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT journals_pkey PRIMARY KEY,
    public_id          uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT journals_public_id_key UNIQUE,
    kind               text        NOT NULL CONSTRAINT journals_kind_check
                                   CHECK (kind IN ('collection', 'adjustment', 'deposit', 'bank_deposit', 'settlement',
                                                   'writeoff', 'reversal', 'opening')),
    business_date      date        NOT NULL,
    status             text        NOT NULL DEFAULT 'pending' CONSTRAINT journals_status_check
                                   CHECK (status IN ('pending', 'posted', 'rejected')),
    source_type        text        NOT NULL,           -- daily_report, receipt, bank_deposit, settlement, manual, import
    source_id          bigint      NOT NULL,
    reverses_id        bigint      CONSTRAINT journals_reverses_id_fkey REFERENCES cash.journals (id),
    reason             text,
    created_by         bigint,
    created_by_device  bigint,
    created_at         timestamptz NOT NULL DEFAULT now(),
    decided_by         bigint,
    decided_at         timestamptz,
    CONSTRAINT journals_reason_check CHECK (kind NOT IN ('adjustment', 'reversal', 'writeoff') OR reason IS NOT NULL),
    CONSTRAINT journals_reversal_check CHECK ((kind = 'reversal') = (reverses_id IS NOT NULL)),
    CONSTRAINT journals_creator_check CHECK (created_by IS NOT NULL OR created_by_device IS NOT NULL)
);
-- At most one live collection per daily report, one deposit per receipt, one settlement per case,
-- and one reversal per journal. A rejected journal frees its source for a new submission.
CREATE UNIQUE INDEX journals_one_per_source ON cash.journals (source_type, source_id, kind)
    WHERE status <> 'rejected' AND kind IN ('collection', 'deposit', 'settlement', 'opening');
CREATE UNIQUE INDEX journals_one_reversal ON cash.journals (reverses_id) WHERE kind = 'reversal';
CREATE INDEX journals_status_idx ON cash.journals (status, created_at);

CREATE TABLE cash.journal_lines (
    journal_id  bigint        NOT NULL CONSTRAINT journal_lines_journal_id_fkey REFERENCES cash.journals (id),
    account_id  bigint        NOT NULL CONSTRAINT journal_lines_account_id_fkey REFERENCES cash.accounts (id),
    amount      numeric(12,3) NOT NULL CONSTRAINT journal_lines_amount_check CHECK (amount <> 0),
    CONSTRAINT journal_lines_pkey PRIMARY KEY (journal_id, account_id)
);
CREATE INDEX journal_lines_account_id_idx ON cash.journal_lines (account_id);

-- Lines are written once, only while their journal is pending, and every journal balances at commit.
CREATE FUNCTION cash.guard_lines() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'journal lines are immutable';
    END IF;
    IF (SELECT status FROM cash.journals WHERE id = NEW.journal_id) <> 'pending' THEN
        RAISE EXCEPTION 'lines can only be added to a pending journal';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER lines_guard BEFORE INSERT OR UPDATE OR DELETE ON cash.journal_lines
    FOR EACH ROW EXECUTE FUNCTION cash.guard_lines();

CREATE FUNCTION cash.check_balanced() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF (SELECT sum(amount) FROM cash.journal_lines WHERE journal_id = NEW.journal_id) <> 0 THEN
        RAISE EXCEPTION 'journal % does not balance', NEW.journal_id;
    END IF;
    RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER lines_balanced AFTER INSERT ON cash.journal_lines
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION cash.check_balanced();

-- Journals are append-only: the only allowed change is pending -> posted / rejected.
CREATE FUNCTION cash.guard_journal() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    decision constant text[] := ARRAY['status', 'decided_by', 'decided_at'];
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'journals are append-only';
    END IF;
    IF OLD.status <> 'pending' OR NEW.status = 'pending'
       OR (to_jsonb(NEW) - decision) <> (to_jsonb(OLD) - decision) THEN
        RAISE EXCEPTION 'only a pending journal can be decided, and only its decision fields may change';
    END IF;
    IF NEW.status = 'posted' AND (SELECT count(*) < 2 OR sum(amount) <> 0
                                  FROM cash.journal_lines WHERE journal_id = NEW.id) THEN
        RAISE EXCEPTION 'journal % cannot be posted without balanced lines', NEW.id;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER journal_guard BEFORE UPDATE OR DELETE ON cash.journals
    FOR EACH ROW EXECUTE FUNCTION cash.guard_journal();

CREATE VIEW cash.balances AS
SELECT l.account_id,
       coalesce(sum(l.amount) FILTER (WHERE j.status = 'posted'), 0)  AS posted,
       coalesce(sum(l.amount) FILTER (WHERE j.status = 'pending'), 0) AS pending
FROM cash.journal_lines l
JOIN cash.journals j ON j.id = l.journal_id
GROUP BY l.account_id;

-- Receipts are numbered by the system per branch, so a receipt number cannot repeat.
CREATE TABLE cash.receipts (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT receipts_pkey PRIMARY KEY,
    public_id            uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT receipts_public_id_key UNIQUE,
    branch_id            bigint        NOT NULL CONSTRAINT receipts_branch_id_fkey REFERENCES org.branches (id),
    receipt_no           integer       NOT NULL,
    driver_id            bigint        NOT NULL CONSTRAINT receipts_driver_id_fkey REFERENCES people.employees (id),
    amount               numeric(12,3) NOT NULL CONSTRAINT receipts_amount_check CHECK (amount > 0),
    created_by           bigint        NOT NULL,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    driver_confirmed_at  timestamptz,
    CONSTRAINT receipts_branch_id_receipt_no_key UNIQUE (branch_id, receipt_no)
);

CREATE TABLE daily_ops.reports (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT reports_pkey PRIMARY KEY,
    public_id            uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT reports_public_id_key UNIQUE,
    employee_id          bigint        NOT NULL CONSTRAINT reports_employee_id_fkey REFERENCES people.employees (id),
    company_id           bigint        NOT NULL,
    custody_id           bigint,
    vehicle_id           bigint,
    business_date        date          NOT NULL,
    orders_count         integer       CONSTRAINT reports_orders_count_check CHECK (orders_count >= 0),
    cash_amount          numeric(12,3) NOT NULL DEFAULT 0 CONSTRAINT reports_cash_amount_check CHECK (cash_amount >= 0),
    screenshot_sha256    text          CONSTRAINT reports_screenshot_sha256_fkey REFERENCES files.files (sha256),
    notes                text,
    status               text          NOT NULL DEFAULT 'submitted' CONSTRAINT reports_status_check
                                       CHECK (status IN ('submitted', 'approved', 'rejected')),
    submitted_at         timestamptz   NOT NULL DEFAULT now(),
    submitted_by_device  bigint,
    reviewed_by          bigint,
    reviewed_at          timestamptz,
    review_note          text,
    approved_cash        numeric(12,3),
    version              integer       NOT NULL DEFAULT 1
);
-- one live report per driver and day; a rejected one can be sent again
CREATE UNIQUE INDEX reports_one_per_day_idx ON daily_ops.reports (employee_id, business_date) WHERE status <> 'rejected';
CREATE INDEX reports_status_idx ON daily_ops.reports (status, submitted_at);

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
