"""M3: maintenance requests, maintenance centers and their portal, repair quotes and invoices (BRD 5.9, 5.10).

A request goes: requested -> approved (or rejected with a reason; an emergency is approved at once and reviewed
afterwards) -> referred to a center -> the center receives the vehicle (arrival time, odometer with its photo,
condition, photos) -> inspection -> quote (approval needed above the limit) -> in repair / waiting for parts ->
completed (final odometer with its photo) -> ready for pickup -> picked up -> closed (once its invoice is approved,
if the settings say so). Every status change is a row in request_events: the time spent at the center and in each
status comes from there. A vehicle is at one center at a time.

Center users are identity users linked to one center; the portal shows them only what was referred to it.

Revision ID: 0009_maintenance
Revises: 0008_cash_daily_ops
"""

from alembic import op

revision = "0009_maintenance"
down_revision = "0008_cash_daily_ops"
branch_labels = None
depends_on = None

SQL = r"""
CREATE SCHEMA maintenance;

-- the readings a center records: at reception when nobody had the vehicle, and at the end of the repair
ALTER TABLE fleet.odometer_readings DROP CONSTRAINT odometer_readings_kind_check;
ALTER TABLE fleet.odometer_readings ADD CONSTRAINT odometer_readings_kind_check
    CHECK (kind IN ('handover', 'return', 'start_day', 'end_day', 'maintenance_in', 'maintenance_out'));

CREATE TABLE maintenance.centers (
    id            bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT centers_pkey PRIMARY KEY,
    public_id     uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT centers_public_id_key UNIQUE,
    name          text        NOT NULL,
    specialty     text,
    contact_name  text,
    phone         text,
    email         text,
    address       text,
    notes         text,
    is_active     boolean     NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    version       integer     NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX centers_name_idx ON maintenance.centers (lower(name));

CREATE TABLE maintenance.center_users (
    user_id     bigint      NOT NULL CONSTRAINT center_users_pkey PRIMARY KEY
                            CONSTRAINT center_users_user_id_fkey REFERENCES identity.users (id) ON DELETE CASCADE,
    center_id   bigint      NOT NULL CONSTRAINT center_users_center_id_fkey REFERENCES maintenance.centers (id),
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX center_users_center_id_idx ON maintenance.center_users (center_id);

CREATE SEQUENCE maintenance.request_number_seq;

CREATE TABLE maintenance.requests (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT requests_pkey PRIMARY KEY,
    public_id              uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT requests_public_id_key UNIQUE,
    number                 integer     NOT NULL DEFAULT nextval('maintenance.request_number_seq')
                                       CONSTRAINT requests_number_key UNIQUE,
    vehicle_id             bigint      NOT NULL CONSTRAINT requests_vehicle_id_fkey REFERENCES fleet.vehicles (id),
    company_id             bigint      NOT NULL,
    driver_id              bigint      CONSTRAINT requests_driver_id_fkey REFERENCES people.employees (id),
    kind                   text        NOT NULL CONSTRAINT requests_kind_check
                                       CHECK (kind IN ('periodic', 'mechanical', 'electrical', 'tyres', 'battery',
                                                       'ac', 'bodywork', 'other')),
    description            text        NOT NULL,
    odometer_km            integer     CONSTRAINT requests_odometer_km_check CHECK (odometer_km >= 0),
    emergency              boolean     NOT NULL DEFAULT false,
    status                 text        NOT NULL DEFAULT 'requested' CONSTRAINT requests_status_check
                                       CHECK (status IN ('requested', 'approved', 'rejected', 'referred', 'received',
                                                         'inspection', 'quote_pending', 'in_repair', 'waiting_parts',
                                                         'completed', 'ready', 'picked_up', 'closed', 'cancelled')),
    client_ref             uuid        CONSTRAINT requests_client_ref_key UNIQUE,  -- the app's id: a retry is known
    created_by_user        bigint,
    created_by_device      bigint,
    created_at             timestamptz NOT NULL DEFAULT now(),
    decided_by             bigint,
    decided_at             timestamptz,
    decision_note          text,
    emergency_reviewed_by  bigint,
    emergency_reviewed_at  timestamptz,
    center_id              bigint      CONSTRAINT requests_center_id_fkey REFERENCES maintenance.centers (id),
    referred_by            bigint,
    referred_at            timestamptz,
    seen_at                timestamptz,                    -- first opened in the center's portal
    received_at            timestamptz,
    received_by            bigint,
    received_km            integer,
    condition_note         text,
    repair_details         text,
    final_km               integer,
    completed_at           timestamptz,
    ready_at               timestamptz,
    picked_up_at           timestamptz,
    picked_up_by           bigint,
    closed_at              timestamptz,
    cancel_reason          text,
    version                integer     NOT NULL DEFAULT 1,
    CONSTRAINT requests_creator_check CHECK (created_by_user IS NOT NULL OR created_by_device IS NOT NULL),
    CONSTRAINT requests_rejected_check CHECK (status <> 'rejected' OR decision_note IS NOT NULL),
    CONSTRAINT requests_cancelled_check CHECK (status <> 'cancelled' OR cancel_reason IS NOT NULL),
    CONSTRAINT requests_center_check
        CHECK (center_id IS NOT NULL OR status IN ('requested', 'approved', 'rejected', 'cancelled'))
);
-- a vehicle is at one center at a time
CREATE UNIQUE INDEX requests_one_at_center_idx ON maintenance.requests (vehicle_id)
    WHERE status IN ('referred', 'received', 'inspection', 'quote_pending', 'in_repair', 'waiting_parts',
                     'completed', 'ready');
CREATE INDEX requests_status_idx ON maintenance.requests (status, created_at);
CREATE INDEX requests_vehicle_id_idx ON maintenance.requests (vehicle_id, created_at);
CREATE INDEX requests_center_id_idx ON maintenance.requests (center_id, status);
CREATE INDEX requests_driver_id_idx ON maintenance.requests (driver_id, created_at);

CREATE TABLE maintenance.request_photos (
    request_id   bigint NOT NULL CONSTRAINT request_photos_request_id_fkey REFERENCES maintenance.requests (id),
    stage        text   NOT NULL CONSTRAINT request_photos_stage_check
                        CHECK (stage IN ('request', 'reception', 'repair')),
    file_sha256  text   NOT NULL CONSTRAINT request_photos_file_sha256_fkey REFERENCES files.files (sha256),
    CONSTRAINT request_photos_pkey PRIMARY KEY (request_id, file_sha256)
);

-- every status change, who and when: the timeline, the approval log and the durations
CREATE TABLE maintenance.request_events (
    id          bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT request_events_pkey PRIMARY KEY,
    request_id  bigint      NOT NULL CONSTRAINT request_events_request_id_fkey REFERENCES maintenance.requests (id),
    status      text        NOT NULL,
    at          timestamptz NOT NULL DEFAULT now(),
    by_user     bigint,
    by_device   bigint,
    note        text
);
CREATE INDEX request_events_request_id_idx ON maintenance.request_events (request_id, at);

CREATE TABLE maintenance.quotes (
    id             bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT quotes_pkey PRIMARY KEY,
    public_id      uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT quotes_public_id_key UNIQUE,
    request_id     bigint        NOT NULL CONSTRAINT quotes_request_id_fkey REFERENCES maintenance.requests (id),
    amount         numeric(12,3) NOT NULL CONSTRAINT quotes_amount_check CHECK (amount > 0),
    items          jsonb         NOT NULL DEFAULT '[]',
    notes          text,
    file_sha256    text          CONSTRAINT quotes_file_sha256_fkey REFERENCES files.files (sha256),
    status         text          NOT NULL DEFAULT 'pending' CONSTRAINT quotes_status_check
                                 CHECK (status IN ('pending', 'approved', 'rejected')),
    auto_approved  boolean       NOT NULL DEFAULT false,   -- within the approval limit
    created_by     bigint        NOT NULL,
    created_at     timestamptz   NOT NULL DEFAULT now(),
    decided_by     bigint,
    decided_at     timestamptz,
    reason         text,
    CONSTRAINT quotes_rejected_check CHECK (status <> 'rejected' OR reason IS NOT NULL)
);
CREATE UNIQUE INDEX quotes_one_pending_idx ON maintenance.quotes (request_id) WHERE status = 'pending';
CREATE INDEX quotes_request_id_idx ON maintenance.quotes (request_id);

CREATE TABLE maintenance.invoices (
    id              bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT invoices_pkey PRIMARY KEY,
    public_id       uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT invoices_public_id_key UNIQUE,
    center_id       bigint        NOT NULL CONSTRAINT invoices_center_id_fkey REFERENCES maintenance.centers (id),
    request_id      bigint        CONSTRAINT invoices_request_id_fkey REFERENCES maintenance.requests (id),
    company_id      bigint        NOT NULL CONSTRAINT invoices_company_id_fkey REFERENCES org.companies (id),
    number          text          NOT NULL,
    invoice_date    date          NOT NULL,
    total           numeric(12,3) NOT NULL CONSTRAINT invoices_total_check CHECK (total > 0),
    file_sha256     text          NOT NULL CONSTRAINT invoices_file_sha256_fkey REFERENCES files.files (sha256),
    notes           text,
    flags           text[]        NOT NULL DEFAULT '{}',    -- duplicate_number, differs_from_quote
    status          text          NOT NULL DEFAULT 'pending' CONSTRAINT invoices_status_check
                                  CHECK (status IN ('pending', 'approved', 'rejected')),
    payment_status  text          NOT NULL DEFAULT 'unpaid' CONSTRAINT invoices_payment_status_check
                                  CHECK (payment_status IN ('unpaid', 'paid')),
    paid_at         timestamptz,
    paid_by         bigint,
    payment_ref     text,
    created_by      bigint        NOT NULL,
    created_at      timestamptz   NOT NULL DEFAULT now(),
    decided_by      bigint,
    decided_at      timestamptz,
    reason          text,
    version         integer       NOT NULL DEFAULT 1,
    CONSTRAINT invoices_rejected_check CHECK (status <> 'rejected' OR reason IS NOT NULL),
    CONSTRAINT invoices_paid_check CHECK ((payment_status = 'paid') = (paid_at IS NOT NULL)),
    CONSTRAINT invoices_paid_approved_check CHECK (payment_status = 'unpaid' OR status = 'approved')
);
-- not unique: a repeated number for the same center is flagged and alerted, never silently refused
CREATE INDEX invoices_center_id_idx ON maintenance.invoices (center_id, lower(number));
CREATE INDEX invoices_status_idx ON maintenance.invoices (status, created_at);
CREATE INDEX invoices_request_id_idx ON maintenance.invoices (request_id);

CREATE TABLE maintenance.invoice_items (
    invoice_id   bigint        NOT NULL CONSTRAINT invoice_items_invoice_id_fkey REFERENCES maintenance.invoices (id),
    line         smallint      NOT NULL,
    kind         text          NOT NULL CONSTRAINT invoice_items_kind_check CHECK (kind IN ('part', 'labour', 'other')),
    description  text          NOT NULL,
    quantity     numeric(10,3) NOT NULL CONSTRAINT invoice_items_quantity_check CHECK (quantity > 0),
    unit_price   numeric(12,3) NOT NULL CONSTRAINT invoice_items_unit_price_check CHECK (unit_price >= 0),
    CONSTRAINT invoice_items_pkey PRIMARY KEY (invoice_id, line)
);

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
