"""M3: accidents (BRD 5.11, UAT-24..26) and the deductions that payroll will apply (BRD 5.14, first part).

An accident is reported from the app (the vehicle the driver held at that moment, camera photos from several
angles) or by the office. The responsible driver comes from the custody log at the accident time. The police report
may come later: until then the accident waits for it, and no liability outcome can be recorded without it (the
database refuses it too). A maintenance center chosen by the maintenance manager estimates the damage in its portal;
the manager approves the estimate; the outcome (no liability, driver, shared) then creates a deduction for the
driver, a share of the approved damage, in monthly installments that payroll will apply.

Revision ID: 0010_accidents
Revises: 0009_maintenance
"""

from alembic import op

revision = "0010_accidents"
down_revision = "0009_maintenance"
branch_labels = None
depends_on = None

SQL = r"""
CREATE SCHEMA accidents;
CREATE SCHEMA payroll;

-- What payroll deducts: a total in monthly installments from a start month, with its source and reason.
-- Approved when created (the approval is the act that creates it); cancelled with a reason, never deleted.
CREATE TABLE payroll.deductions (
    id            bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT deductions_pkey PRIMARY KEY,
    public_id     uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT deductions_public_id_key UNIQUE,
    employee_id   bigint        NOT NULL CONSTRAINT deductions_employee_id_fkey REFERENCES people.employees (id),
    company_id    bigint        NOT NULL,
    source_type   text          NOT NULL CONSTRAINT deductions_source_type_check
                                CHECK (source_type IN ('accident', 'fine', 'other')),
    source_id     bigint,
    reason        text          NOT NULL,
    total         numeric(12,3) NOT NULL CONSTRAINT deductions_total_check CHECK (total > 0),
    installments  smallint      NOT NULL CONSTRAINT deductions_installments_check CHECK (installments BETWEEN 1 AND 60),
    start_month   date          NOT NULL CONSTRAINT deductions_start_month_check
                                CHECK (extract(day FROM start_month) = 1),
    status        text          NOT NULL DEFAULT 'approved' CONSTRAINT deductions_status_check
                                CHECK (status IN ('approved', 'cancelled')),
    created_by    bigint        NOT NULL,
    created_at    timestamptz   NOT NULL DEFAULT now(),
    cancelled_by  bigint,
    cancelled_at  timestamptz,
    cancel_reason text,
    CONSTRAINT deductions_cancelled_check CHECK (status <> 'cancelled' OR cancel_reason IS NOT NULL)
);
-- one live deduction per source (an accident is charged once)
CREATE UNIQUE INDEX deductions_one_per_source_idx ON payroll.deductions (source_type, source_id)
    WHERE status <> 'cancelled' AND source_id IS NOT NULL;
CREATE INDEX deductions_employee_id_idx ON payroll.deductions (employee_id, start_month);

CREATE SEQUENCE accidents.accident_number_seq;

CREATE TABLE accidents.accidents (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT accidents_pkey PRIMARY KEY,
    public_id               uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT accidents_public_id_key UNIQUE,
    number                  integer       NOT NULL DEFAULT nextval('accidents.accident_number_seq')
                                          CONSTRAINT accidents_number_key UNIQUE,
    vehicle_id              bigint        NOT NULL CONSTRAINT accidents_vehicle_id_fkey REFERENCES fleet.vehicles (id),
    company_id              bigint        NOT NULL,
    driver_id               bigint        CONSTRAINT accidents_driver_id_fkey REFERENCES people.employees (id),
    custody_id              bigint        CONSTRAINT accidents_custody_id_fkey REFERENCES fleet.custodies (id),
    occurred_at             timestamptz   NOT NULL,
    lat                     double precision,
    lng                     double precision,
    location_text           text,
    description             text          NOT NULL,
    injuries                boolean       NOT NULL DEFAULT false,
    injuries_note           text,
    other_party             text,
    client_ref              uuid          CONSTRAINT accidents_client_ref_key UNIQUE,
    reported_by_user        bigint,
    reported_by_device      bigint,
    created_at              timestamptz   NOT NULL DEFAULT now(),
    police_report_sha256    text          CONSTRAINT accidents_police_report_sha256_fkey REFERENCES files.files (sha256),
    police_report_no        text,
    police_report_at        timestamptz,
    center_id               bigint        CONSTRAINT accidents_center_id_fkey REFERENCES maintenance.centers (id),
    referred_by             bigint,
    referred_at             timestamptz,
    seen_at                 timestamptz,
    estimate_status         text          NOT NULL DEFAULT 'none' CONSTRAINT accidents_estimate_status_check
                                          CHECK (estimate_status IN ('none', 'pending', 'approved', 'rejected')),
    estimate_total          numeric(12,3) CONSTRAINT accidents_estimate_total_check CHECK (estimate_total > 0),
    estimate_items          jsonb         NOT NULL DEFAULT '[]',
    estimate_notes          text,
    estimate_file_sha256    text          CONSTRAINT accidents_estimate_file_sha256_fkey REFERENCES files.files (sha256),
    estimated_by            bigint,
    estimated_at            timestamptz,
    estimate_decided_by     bigint,
    estimate_decided_at     timestamptz,
    estimate_reason         text,
    liability               text          CONSTRAINT accidents_liability_check
                                          CHECK (liability IN ('none', 'driver', 'shared')),
    liability_percent       numeric(5,2)  CONSTRAINT accidents_liability_percent_check
                                          CHECK (liability_percent > 0 AND liability_percent <= 100),
    outcome_note            text,
    outcome_by              bigint,
    outcome_at              timestamptz,
    deduction_id            bigint        CONSTRAINT accidents_deduction_id_fkey REFERENCES payroll.deductions (id),
    repair_request_id       bigint        CONSTRAINT accidents_repair_request_id_fkey REFERENCES maintenance.requests (id),
    status                  text          NOT NULL DEFAULT 'open' CONSTRAINT accidents_status_check
                                          CHECK (status IN ('open', 'closed', 'cancelled')),
    closed_at               timestamptz,
    cancel_reason           text,
    version                 integer       NOT NULL DEFAULT 1,
    CONSTRAINT accidents_reporter_check CHECK (reported_by_user IS NOT NULL OR reported_by_device IS NOT NULL),
    -- UAT-24: no outcome without the police report, whoever writes
    CONSTRAINT accidents_outcome_check CHECK (liability IS NULL OR police_report_sha256 IS NOT NULL),
    CONSTRAINT accidents_estimate_check CHECK (estimate_status = 'none' OR center_id IS NOT NULL),
    CONSTRAINT accidents_cancelled_check CHECK (status <> 'cancelled' OR cancel_reason IS NOT NULL)
);
CREATE INDEX accidents_status_idx ON accidents.accidents (status, occurred_at);
CREATE INDEX accidents_vehicle_id_idx ON accidents.accidents (vehicle_id, occurred_at);
CREATE INDEX accidents_driver_id_idx ON accidents.accidents (driver_id, occurred_at);
CREATE INDEX accidents_center_id_idx ON accidents.accidents (center_id, estimate_status);

CREATE TABLE accidents.accident_photos (
    accident_id  bigint NOT NULL CONSTRAINT accident_photos_accident_id_fkey REFERENCES accidents.accidents (id),
    file_sha256  text   NOT NULL CONSTRAINT accident_photos_file_sha256_fkey REFERENCES files.files (sha256),
    CONSTRAINT accident_photos_pkey PRIMARY KEY (accident_id, file_sha256)
);

CREATE TABLE accidents.accident_events (
    id           bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT accident_events_pkey PRIMARY KEY,
    accident_id  bigint      NOT NULL CONSTRAINT accident_events_accident_id_fkey REFERENCES accidents.accidents (id),
    kind         text        NOT NULL,
    at           timestamptz NOT NULL DEFAULT now(),
    by_user      bigint,
    by_device    bigint,
    note         text
);
CREATE INDEX accident_events_accident_id_idx ON accidents.accident_events (accident_id, at);

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
