"""M3: traffic fines (BRD FR-VEH-06, FR-PAY-02, UAT-12).

A fine is registered with its date and time (the ticket number, the violation, the amount, a scan of the ticket); the
driver responsible is whoever held the vehicle at that moment, from the custody log. Then it is decided once: charged
to the driver as an approved deduction in monthly installments (by the holder of deductions.manage), or borne by the
company with a reason, or cancelled (a wrong entry). Whether and when the company paid the traffic department is
recorded apart. A ticket number is entered once.

Revision ID: 0011_fines
Revises: 0010_accidents
"""

from alembic import op

revision = "0011_fines"
down_revision = "0010_accidents"
branch_labels = None
depends_on = None

SQL = r"""
CREATE SCHEMA fines;

CREATE SEQUENCE fines.fine_number_seq;

CREATE TABLE fines.fines (
    id               bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT fines_pkey PRIMARY KEY,
    public_id        uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT fines_public_id_key UNIQUE,
    number           integer       NOT NULL DEFAULT nextval('fines.fine_number_seq') CONSTRAINT fines_number_key UNIQUE,
    vehicle_id       bigint        NOT NULL CONSTRAINT fines_vehicle_id_fkey REFERENCES fleet.vehicles (id),
    company_id       bigint        NOT NULL,
    driver_id        bigint        CONSTRAINT fines_driver_id_fkey REFERENCES people.employees (id),
    custody_id       bigint        CONSTRAINT fines_custody_id_fkey REFERENCES fleet.custodies (id),
    occurred_at      timestamptz   NOT NULL,
    reference_no     text,
    violation        text          NOT NULL,
    location_text    text,
    amount           numeric(12,3) NOT NULL CONSTRAINT fines_amount_check CHECK (amount > 0),
    file_sha256      text          CONSTRAINT fines_file_sha256_fkey REFERENCES files.files (sha256),
    notes            text,
    status           text          NOT NULL DEFAULT 'open' CONSTRAINT fines_status_check
                                   CHECK (status IN ('open', 'charged', 'company', 'cancelled')),
    decided_by       bigint,
    decided_at       timestamptz,
    decision_note    text,
    deduction_id     bigint        CONSTRAINT fines_deduction_id_fkey REFERENCES payroll.deductions (id),
    paid_at          timestamptz,
    paid_by          bigint,
    payment_ref      text,
    created_by       bigint        NOT NULL,
    created_at       timestamptz   NOT NULL DEFAULT now(),
    cancel_reason    text,
    version          integer       NOT NULL DEFAULT 1,
    CONSTRAINT fines_charged_check CHECK (status <> 'charged' OR (deduction_id IS NOT NULL AND driver_id IS NOT NULL)),
    CONSTRAINT fines_company_check CHECK (status <> 'company' OR decision_note IS NOT NULL),
    CONSTRAINT fines_cancelled_check CHECK (status <> 'cancelled' OR cancel_reason IS NOT NULL),
    CONSTRAINT fines_paid_check CHECK ((paid_at IS NULL) = (paid_by IS NULL))
);
-- a ticket is entered once (a cancelled wrong entry frees its number)
CREATE UNIQUE INDEX fines_reference_no_idx ON fines.fines (lower(reference_no))
    WHERE reference_no IS NOT NULL AND status <> 'cancelled';
CREATE INDEX fines_status_idx ON fines.fines (status, occurred_at);
CREATE INDEX fines_vehicle_id_idx ON fines.fines (vehicle_id, occurred_at);
CREATE INDEX fines_driver_id_idx ON fines.fines (driver_id, occurred_at);

-- who works with fines in the role templates: the supervisor registers them, HR and the accountant see them
-- (HR charges them to the driver with deductions.manage; the accountant records the payment with finance.create)
INSERT INTO identity.role_permissions (role_id, permission)
SELECT id, 'fines.manage' FROM identity.roles WHERE code = 'supervisor'
ON CONFLICT DO NOTHING;
INSERT INTO identity.role_permissions (role_id, permission)
SELECT id, 'fines.view' FROM identity.roles WHERE code IN ('hr', 'accountant')
ON CONFLICT DO NOTHING;

CREATE OR REPLACE FUNCTION public.fleet_apply_grants() RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    s text;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fleet_app') THEN
        RETURN;
    END IF;
    FOR s IN SELECT nspname FROM pg_namespace
             WHERE nspname = ANY (ARRAY['org', 'identity', 'audit', 'integrations', 'i18n', 'files', 'people',
                                        'documents', 'fleet', 'tracking', 'onboarding', 'daily_ops', 'cash',
                                        'maintenance', 'accidents', 'fines', 'payroll', 'finance', 'approvals',
                                        'notifications', 'reports'])
    LOOP
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO fleet_app', s);
        EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO fleet_app', s);
        IF s = 'audit' THEN
            EXECUTE 'GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA audit TO fleet_app';
        ELSE
            EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO fleet_app', s);
        END IF;
    END LOOP;
    IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'tracking') THEN
        EXECUTE 'GRANT EXECUTE ON FUNCTION tracking.ensure_month_partition(date), '
                'tracking.drop_partitions_before(date) TO fleet_app';
    END IF;
    EXECUTE 'ALTER ROLE fleet_app SET statement_timeout = ''30s''';
END $$;

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
