"""Payroll (BRD 5.14): delivery platforms, the driver's monthly platform statement, and the monthly payroll run.

- payroll.platforms: the delivery platforms the drivers work on, as data. Each one has its pay rule (the basic salary,
  rates per order, hour or valid day, how a day the platform did not count is deducted) and its salary sheet: the
  columns in order with the client's own headers, read from the client's template.
- people.employees: the driver's platform and his ID there, the bank name and how he is paid.
- payroll.statements: what a platform says about a driver's month (valid days, orders, hours), sent by the driver
  with screenshots from the platform's app or entered by the office, then reviewed: payroll uses only approved
  figures. Bonus, tips and the platform's deductions are entered by the office from the platform's settlement.
- payroll.runs / lines / line_deductions: one run per company and month. Lines are recomputed freely while the run
  is a draft; approval locks the run and the month's statements, and what each deduction actually took that month
  is what the next months build on (the rest of a capped month moves on, FR-PAY-03).
- Deductions gain two sources the office enters itself: advances and phone SIM cards.

Revision ID: 0014_platforms_payroll
Revises: 0013_drivers_without_phone
"""

from alembic import op

revision = "0014_platforms_payroll"
down_revision = "0013_drivers_without_phone"
branch_labels = None
depends_on = None

SQL = r"""
CREATE TABLE payroll.platforms (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT platforms_pkey PRIMARY KEY,
    public_id           uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT platforms_public_id_key UNIQUE,
    code                text          NOT NULL CONSTRAINT platforms_code_key UNIQUE
                                      CONSTRAINT platforms_code_check CHECK (code ~ '^[a-z][a-z0-9_]{1,30}$'),
    name                jsonb         NOT NULL,
    is_active           boolean       NOT NULL DEFAULT true,
    driver_fields       text[]        NOT NULL DEFAULT '{}' CONSTRAINT platforms_driver_fields_check
                                      CHECK (driver_fields <@ ARRAY['valid_days', 'orders', 'hours']::text[]),
    pay_basic           boolean       NOT NULL DEFAULT true,
    per_order           numeric(12,3) NOT NULL DEFAULT 0 CONSTRAINT platforms_per_order_check CHECK (per_order >= 0),
    per_hour            numeric(12,3) NOT NULL DEFAULT 0 CONSTRAINT platforms_per_hour_check CHECK (per_hour >= 0),
    per_valid_day       numeric(12,3) NOT NULL DEFAULT 0
                                      CONSTRAINT platforms_per_valid_day_check CHECK (per_valid_day >= 0),
    invalid_days        text          NOT NULL DEFAULT 'none' CONSTRAINT platforms_invalid_days_check
                                      CHECK (invalid_days IN ('none', 'daily_wage', 'fixed')),
    invalid_day_amount  numeric(12,3) CONSTRAINT platforms_invalid_day_amount_check CHECK (invalid_day_amount >= 0),
    day_divisor         smallint      NOT NULL DEFAULT 30
                                      CONSTRAINT platforms_day_divisor_check CHECK (day_divisor BETWEEN 1 AND 31),
    columns             jsonb         NOT NULL DEFAULT '[]'::jsonb,
    created_at          timestamptz   NOT NULL DEFAULT now(),
    version             integer       NOT NULL DEFAULT 1,
    CONSTRAINT platforms_fixed_check CHECK (invalid_days <> 'fixed' OR invalid_day_amount IS NOT NULL)
);

ALTER TABLE people.employees
    ADD COLUMN bank_name          text,
    ADD COLUMN payment_method     text CONSTRAINT employees_payment_method_check
                                       CHECK (payment_method IN ('bank', 'cash')),
    ADD COLUMN platform_id        bigint CONSTRAINT employees_platform_id_fkey REFERENCES payroll.platforms (id),
    ADD COLUMN platform_driver_id text,
    ADD CONSTRAINT employees_platform_driver_check CHECK (platform_driver_id IS NULL OR platform_id IS NOT NULL);
-- a driver's ID is unique on its platform
CREATE UNIQUE INDEX employees_platform_driver_id_idx ON people.employees (platform_id, lower(platform_driver_id))
    WHERE platform_driver_id IS NOT NULL;

ALTER TABLE payroll.deductions DROP CONSTRAINT deductions_source_type_check;
ALTER TABLE payroll.deductions ADD CONSTRAINT deductions_source_type_check
    CHECK (source_type IN ('accident', 'fine', 'advance', 'sim', 'other'));

CREATE TABLE payroll.statements (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT statements_pkey PRIMARY KEY,
    public_id            uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT statements_public_id_key UNIQUE,
    employee_id          bigint        NOT NULL CONSTRAINT statements_employee_id_fkey REFERENCES people.employees (id),
    company_id           bigint        NOT NULL,
    platform_id          bigint        CONSTRAINT statements_platform_id_fkey REFERENCES payroll.platforms (id),
    month                date          NOT NULL CONSTRAINT statements_month_check CHECK (extract(day FROM month) = 1),
    status               text          NOT NULL DEFAULT 'submitted' CONSTRAINT statements_status_check
                                       CHECK (status IN ('submitted', 'approved', 'rejected')),
    declared             jsonb         NOT NULL DEFAULT '{}'::jsonb,
    working_days         smallint      CONSTRAINT statements_working_days_check CHECK (working_days BETWEEN 0 AND 31),
    valid_days           smallint      CONSTRAINT statements_valid_days_check CHECK (valid_days BETWEEN 0 AND 31),
    orders               integer       CONSTRAINT statements_orders_check CHECK (orders >= 0),
    hours                numeric(6,2)  CONSTRAINT statements_hours_check CHECK (hours BETWEEN 0 AND 744),
    bonus                numeric(12,3) NOT NULL DEFAULT 0 CONSTRAINT statements_bonus_check CHECK (bonus >= 0),
    tips                 numeric(12,3) NOT NULL DEFAULT 0 CONSTRAINT statements_tips_check CHECK (tips >= 0),
    cancelled_orders     numeric(12,3) NOT NULL DEFAULT 0
                                       CONSTRAINT statements_cancelled_orders_check CHECK (cancelled_orders >= 0),
    platform_deductions  numeric(12,3) NOT NULL DEFAULT 0
                                       CONSTRAINT statements_platform_deductions_check CHECK (platform_deductions >= 0),
    late                 numeric(12,3) NOT NULL DEFAULT 0 CONSTRAINT statements_late_check CHECK (late >= 0),
    cash_shortage        numeric(12,3) NOT NULL DEFAULT 0
                                       CONSTRAINT statements_cash_shortage_check CHECK (cash_shortage >= 0),
    submitted_at         timestamptz   NOT NULL DEFAULT now(),
    submitted_by_device  bigint,
    submitted_by_user    bigint,
    reviewed_by          bigint,
    reviewed_at          timestamptz,
    review_note          text,
    version              integer       NOT NULL DEFAULT 1,
    CONSTRAINT statements_rejected_check CHECK (status <> 'rejected' OR review_note IS NOT NULL),
    CONSTRAINT statements_source_check CHECK (submitted_by_device IS NOT NULL OR submitted_by_user IS NOT NULL)
);
-- one live statement per driver and month (a rejected one is sent again)
CREATE UNIQUE INDEX statements_one_per_month_idx ON payroll.statements (employee_id, month) WHERE status <> 'rejected';
CREATE INDEX statements_month_idx ON payroll.statements (month, status);

CREATE TABLE payroll.statement_files (
    statement_id  bigint   NOT NULL CONSTRAINT statement_files_statement_id_fkey REFERENCES payroll.statements (id),
    sha256        text     NOT NULL CONSTRAINT statement_files_sha256_fkey REFERENCES files.files (sha256),
    position      smallint NOT NULL,
    CONSTRAINT statement_files_pkey PRIMARY KEY (statement_id, sha256)
);

CREATE TABLE payroll.runs (
    id              bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT runs_pkey PRIMARY KEY,
    public_id       uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT runs_public_id_key UNIQUE,
    company_id      bigint        NOT NULL CONSTRAINT runs_company_id_fkey REFERENCES org.companies (id),
    month           date          NOT NULL CONSTRAINT runs_month_check CHECK (extract(day FROM month) = 1),
    status          text          NOT NULL DEFAULT 'draft' CONSTRAINT runs_status_check
                                  CHECK (status IN ('draft', 'approved', 'paid')),
    cap_percent     numeric(5,2)  NOT NULL,
    cap_base        text          NOT NULL CONSTRAINT runs_cap_base_check CHECK (cap_base IN ('basic', 'gross')),
    totals          jsonb         NOT NULL DEFAULT '{}'::jsonb,
    prepared_by     bigint        NOT NULL,
    prepared_at     timestamptz   NOT NULL DEFAULT now(),
    approved_by     bigint,
    approved_at     timestamptz,
    paid_by         bigint,
    paid_at         timestamptz,
    payment_ref     text,
    reopened        integer       NOT NULL DEFAULT 0,
    version         integer       NOT NULL DEFAULT 1,
    CONSTRAINT runs_company_id_key UNIQUE (company_id, month),
    CONSTRAINT runs_approved_check CHECK (status = 'draft' OR approved_at IS NOT NULL),
    CONSTRAINT runs_paid_check CHECK (status <> 'paid' OR paid_at IS NOT NULL)
);

CREATE TABLE payroll.lines (
    id            bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT lines_pkey PRIMARY KEY,
    run_id        bigint        NOT NULL CONSTRAINT lines_run_id_fkey REFERENCES payroll.runs (id) ON DELETE CASCADE,
    employee_id   bigint        NOT NULL CONSTRAINT lines_employee_id_fkey REFERENCES people.employees (id),
    platform_id   bigint        CONSTRAINT lines_platform_id_fkey REFERENCES payroll.platforms (id),
    statement_id  bigint        CONSTRAINT lines_statement_id_fkey REFERENCES payroll.statements (id),
    cells         jsonb         NOT NULL,
    gross         numeric(12,3) NOT NULL,
    deductions    numeric(12,3) NOT NULL,
    net           numeric(12,3) NOT NULL,
    flags         text[]        NOT NULL DEFAULT '{}',
    CONSTRAINT lines_run_id_key UNIQUE (run_id, employee_id)
);
CREATE INDEX lines_employee_id_idx ON payroll.lines (employee_id);

CREATE TABLE payroll.line_deductions (
    line_id       bigint        NOT NULL CONSTRAINT line_deductions_line_id_fkey REFERENCES payroll.lines (id)
                                ON DELETE CASCADE,
    deduction_id  bigint        NOT NULL CONSTRAINT line_deductions_deduction_id_fkey
                                REFERENCES payroll.deductions (id),
    due           numeric(12,3) NOT NULL,
    deducted      numeric(12,3) NOT NULL CONSTRAINT line_deductions_deducted_check CHECK (deducted >= 0),
    CONSTRAINT line_deductions_pkey PRIMARY KEY (line_id, deduction_id)
);
CREATE INDEX line_deductions_deduction_id_idx ON payroll.line_deductions (deduction_id);

-- who works with payroll in the role templates: HR prepares it (statements and runs), the accountant sees and
-- exports it; approving and reopening stay with the system administrator until the client assigns them
INSERT INTO identity.role_permissions (role_id, permission)
SELECT r.id, p.permission FROM identity.roles r
CROSS JOIN (VALUES ('payroll.view'), ('payroll.prepare')) AS p (permission)
WHERE r.code = 'hr'
ON CONFLICT DO NOTHING;
INSERT INTO identity.role_permissions (role_id, permission)
SELECT r.id, p.permission FROM identity.roles r
CROSS JOIN (VALUES ('payroll.view'), ('payroll.export')) AS p (permission)
WHERE r.code = 'accountant'
ON CONFLICT DO NOTHING;

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
