"""A driver imported without a phone signs in once with his civil ID and an initial password set by the office, then
registers his phone (verified by a WhatsApp code), and the self-registration review follows as for an activation link.

The initial password is single-use and expires; five wrong tries lock the claim for half an hour, and failed tries
per network address are capped. Only a hash is stored. The phone entered is bound only once its code is verified, and
nothing he sends reaches the official records before the reviewer approves it.

Revision ID: 0015_driver_claims
Revises: 0014_platforms_payroll
"""

from alembic import op

revision = "0015_driver_claims"
down_revision = "0014_platforms_payroll"
branch_labels = None
depends_on = None

SQL = r"""
CREATE TABLE identity.driver_claims (
    employee_id         bigint      CONSTRAINT driver_claims_pkey PRIMARY KEY
                                    CONSTRAINT driver_claims_employee_id_fkey REFERENCES people.employees (id),
    password_hash       text        NOT NULL,
    expires_at          timestamptz NOT NULL,
    created_by          bigint      NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    failures            smallint    NOT NULL DEFAULT 0,
    locked_until        timestamptz,
    session_hash        text,
    session_device_uid  text,
    session_expires_at  timestamptz,
    phone               text,
    otp_hash            text,
    otp_expires_at      timestamptz,
    otp_sent            smallint    NOT NULL DEFAULT 0,
    otp_attempts        smallint    NOT NULL DEFAULT 0,
    used_at             timestamptz,
    used_phone          text,
    used_device_id      bigint      CONSTRAINT driver_claims_used_device_id_fkey REFERENCES identity.devices (id)
);
CREATE UNIQUE INDEX driver_claims_session_hash_idx ON identity.driver_claims (session_hash)
    WHERE session_hash IS NOT NULL;

CREATE TABLE identity.claim_attempts (
    id   bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT claim_attempts_pkey PRIMARY KEY,
    ip   text,
    ok   boolean     NOT NULL,
    at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX claim_attempts_ip_idx ON identity.claim_attempts (ip, at);

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
