"""Absence and leave (BRD BR-18, FR-HR-06, FR-PAY-01).

Absence is never recorded on its own: a working day on which a driver neither started his day in the app nor sent a
daily report is listed for HR, who marks it (absence, leave, rest day, no vehicle, or a system fault). Leaves are
registered for a range of days and approved or rejected with a note; an approved leave covers its days. Payroll counts
the month's absence days and unpaid leave days, and deducts them only as the payroll settings say (the client's
decision, section 7.2 of the BRD: no deduction until it is set).

Revision ID: 0019_attendance
Revises: 0018_pay_schemes
"""

from alembic import op

revision = "0019_attendance"
down_revision = "0018_pay_schemes"
branch_labels = None
depends_on = None

SQL = r"""
CREATE SCHEMA attendance;

CREATE TABLE attendance.leaves (
    id             bigint      GENERATED BY DEFAULT AS IDENTITY CONSTRAINT leaves_pkey PRIMARY KEY,
    public_id      uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT leaves_public_id_key UNIQUE,
    employee_id    bigint      NOT NULL CONSTRAINT leaves_employee_id_fkey REFERENCES people.employees (id),
    company_id     bigint      NOT NULL,
    kind           text        NOT NULL CONSTRAINT leaves_kind_check
                                   CHECK (kind IN ('annual', 'sick', 'emergency', 'unpaid', 'other')),
    date_from      date        NOT NULL,
    date_to        date        NOT NULL,
    status         text        NOT NULL DEFAULT 'pending' CONSTRAINT leaves_status_check
                                   CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
    note           text,
    file_sha256    text        CONSTRAINT leaves_file_sha256_fkey REFERENCES files.files (sha256),
    created_by     bigint      NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    decided_by     bigint,
    decided_at     timestamptz,
    decision_note  text,
    cancel_reason  text,
    version        integer     NOT NULL DEFAULT 1,
    CONSTRAINT leaves_range_check CHECK (date_to >= date_from),
    CONSTRAINT leaves_decided_check CHECK ((status = 'pending') = (decided_at IS NULL) OR status = 'cancelled'),
    CONSTRAINT leaves_rejected_check CHECK (status <> 'rejected' OR decision_note IS NOT NULL),
    CONSTRAINT leaves_cancelled_check CHECK (status <> 'cancelled' OR cancel_reason IS NOT NULL)
);
CREATE INDEX leaves_employee_id_idx ON attendance.leaves (employee_id, date_from);
CREATE INDEX leaves_status_idx ON attendance.leaves (status, date_from);

-- one mark per employee and day; a change replaces it (and is in the audit log)
CREATE TABLE attendance.day_marks (
    employee_id  bigint      NOT NULL CONSTRAINT day_marks_employee_id_fkey REFERENCES people.employees (id),
    day          date        NOT NULL,
    kind         text        NOT NULL CONSTRAINT day_marks_kind_check
                                 CHECK (kind IN ('absence', 'leave', 'rest', 'no_vehicle', 'system_fault')),
    note         text,
    marked_by    bigint      NOT NULL,
    marked_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT day_marks_pkey PRIMARY KEY (employee_id, day)
);
CREATE INDEX day_marks_day_idx ON attendance.day_marks (day);

CREATE OR REPLACE FUNCTION public.fleet_apply_grants() RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    s text;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fleet_app') THEN
        RETURN;
    END IF;
    FOR s IN SELECT nspname FROM pg_namespace
             WHERE nspname = ANY (ARRAY['org', 'identity', 'audit', 'integrations', 'i18n', 'files', 'people',
                                        'documents', 'fleet', 'tracking', 'onboarding', 'daily_ops', 'cash',
                                        'maintenance', 'accidents', 'fines', 'payroll', 'attendance', 'finance',
                                        'approvals', 'notifications', 'reports'])
    LOOP
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO fleet_app', s);
        EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO fleet_app', s);
        IF s = 'audit' THEN
            EXECUTE 'GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA audit TO fleet_app';
        ELSE
            EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO fleet_app', s);
        END IF;
    END LOOP;
    IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'tracking') THEN
        EXECUTE 'GRANT EXECUTE ON FUNCTION tracking.ensure_month_partition(date), '
                'tracking.drop_partitions_before(date) TO fleet_app';
    END IF;
    EXECUTE 'ALTER ROLE fleet_app SET statement_timeout = ''30s''';
END $$;

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
