"""Finance (BRD FR-FIN-01..05): expenses, and simple double-entry journal entries made from the documents the system
already has, on a chart of accounts the client's accountant sets.

The chart is data: accounts with codes and names, and roles ("treasury", "salaries payable"...) that say which account
each posting uses; the accountant replaces the default codes with his own and points the roles at them. Entries are
made by the system from posted cash journals (collections, receipts, deposits, adjustments), expenses and their
payment, maintenance invoices and their payment, approved payroll runs, approved deductions and fines paid to the
traffic department: one entry per document. An entry starts as a draft (made again if the chart changes), is approved
by the accountant, and an approved entry never changes: a correction is a reversing entry, which frees the document to
be entered again. Every guard is in the database itself.

Revision ID: 0021_finance
Revises: 0020_rate_limits
"""

from alembic import op

revision = "0021_finance"
down_revision = "0020_rate_limits"
branch_labels = None
depends_on = None

SQL = r"""
CREATE SCHEMA finance;

CREATE TABLE finance.accounts (
    id          bigint      GENERATED BY DEFAULT AS IDENTITY CONSTRAINT accounts_pkey PRIMARY KEY,
    code        text        NOT NULL CONSTRAINT accounts_code_key UNIQUE
                            CONSTRAINT accounts_code_check CHECK (code ~ '^[0-9A-Za-z][0-9A-Za-z.\-]{0,19}$'),
    name        jsonb       NOT NULL,
    type        text        NOT NULL CONSTRAINT accounts_type_check
                            CHECK (type IN ('asset', 'liability', 'equity', 'income', 'expense')),
    active      boolean     NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now(),
    version     integer     NOT NULL DEFAULT 1
);

CREATE TABLE finance.account_roles (
    role        text   CONSTRAINT account_roles_pkey PRIMARY KEY,
    account_id  bigint NOT NULL CONSTRAINT account_roles_account_id_fkey REFERENCES finance.accounts (id)
);

CREATE TABLE finance.expense_types (
    id          bigint  GENERATED BY DEFAULT AS IDENTITY CONSTRAINT expense_types_pkey PRIMARY KEY,
    code        text    NOT NULL CONSTRAINT expense_types_code_key UNIQUE
                        CONSTRAINT expense_types_code_check CHECK (code ~ '^[a-z][a-z0-9_]{1,30}$'),
    name        jsonb   NOT NULL,
    account_id  bigint  NOT NULL CONSTRAINT expense_types_account_id_fkey REFERENCES finance.accounts (id),
    active      boolean NOT NULL DEFAULT true,
    sort_order  integer NOT NULL DEFAULT 100
);

CREATE SEQUENCE finance.expense_number_seq;
CREATE TABLE finance.expenses (
    id              bigint        GENERATED BY DEFAULT AS IDENTITY CONSTRAINT expenses_pkey PRIMARY KEY,
    public_id       uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT expenses_public_id_key UNIQUE,
    number          integer       NOT NULL DEFAULT nextval('finance.expense_number_seq')
                                  CONSTRAINT expenses_number_key UNIQUE,
    company_id      bigint        NOT NULL CONSTRAINT expenses_company_id_fkey REFERENCES org.companies (id),
    type_id         bigint        NOT NULL CONSTRAINT expenses_type_id_fkey REFERENCES finance.expense_types (id),
    expense_date    date          NOT NULL,
    amount          numeric(12,3) NOT NULL CONSTRAINT expenses_amount_check CHECK (amount > 0),
    quantity        numeric(10,2) CONSTRAINT expenses_quantity_check CHECK (quantity > 0),  -- litres of fuel
    payment_method  text          NOT NULL CONSTRAINT expenses_payment_method_check
                                  CHECK (payment_method IN ('treasury', 'bank', 'payable')),
    supplier        text,
    reference_no    text,
    vehicle_id      bigint        CONSTRAINT expenses_vehicle_id_fkey REFERENCES fleet.vehicles (id),
    employee_id     bigint        CONSTRAINT expenses_employee_id_fkey REFERENCES people.employees (id),
    center_id       bigint        CONSTRAINT expenses_center_id_fkey REFERENCES maintenance.centers (id),
    notes           text,
    status          text          NOT NULL DEFAULT 'pending' CONSTRAINT expenses_status_check
                                  CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
    created_by      bigint        NOT NULL,
    created_at      timestamptz   NOT NULL DEFAULT now(),
    decided_by      bigint,
    decided_at      timestamptz,
    decision_note   text,
    cancel_reason   text,
    paid_from       text          CONSTRAINT expenses_paid_from_check CHECK (paid_from IN ('treasury', 'bank')),
    paid_at         timestamptz,
    paid_by         bigint,
    payment_ref     text,
    version         integer       NOT NULL DEFAULT 1,
    CONSTRAINT expenses_rejected_check CHECK (status <> 'rejected' OR decision_note IS NOT NULL),
    CONSTRAINT expenses_cancelled_check CHECK (status <> 'cancelled' OR cancel_reason IS NOT NULL),
    CONSTRAINT expenses_decided_check CHECK (status NOT IN ('approved', 'rejected') OR decided_at IS NOT NULL),
    CONSTRAINT expenses_undecided_check CHECK (status <> 'pending' OR decided_at IS NULL),
    -- paid on the spot (treasury, bank) or later (payable: a supplier's invoice), and only once approved
    CONSTRAINT expenses_paid_check CHECK ((paid_at IS NULL) = (paid_from IS NULL)),
    CONSTRAINT expenses_paid_payable_check CHECK (paid_at IS NULL OR (payment_method = 'payable' AND status = 'approved'))
);
CREATE INDEX expenses_status_idx ON finance.expenses (status, expense_date);
CREATE INDEX expenses_vehicle_id_idx ON finance.expenses (vehicle_id);

CREATE TABLE finance.expense_files (
    expense_id  bigint   NOT NULL CONSTRAINT expense_files_expense_id_fkey REFERENCES finance.expenses (id),
    sha256      text     NOT NULL CONSTRAINT expense_files_sha256_fkey REFERENCES files.files (sha256),
    position    smallint NOT NULL,
    CONSTRAINT expense_files_pkey PRIMARY KEY (expense_id, sha256)
);

CREATE SEQUENCE finance.entry_number_seq;
CREATE TABLE finance.entries (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY CONSTRAINT entries_pkey PRIMARY KEY,
    public_id       uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT entries_public_id_key UNIQUE,
    number          integer     NOT NULL DEFAULT nextval('finance.entry_number_seq') CONSTRAINT entries_number_key UNIQUE,
    entry_date      date        NOT NULL,
    source_kind     text        NOT NULL CONSTRAINT entries_source_kind_check
                                CHECK (source_kind IN ('cash_journal', 'expense', 'expense_payment', 'maintenance_invoice',
                                                       'invoice_payment', 'payroll_run', 'payroll_payment', 'deduction',
                                                       'fine_payment', 'reversal')),
    source_id       bigint,
    source_ref      text        NOT NULL,                 -- what the document is called, for people
    company_id      bigint,                               -- none for a branch's treasury and bank
    description     text        NOT NULL,
    status          text        NOT NULL DEFAULT 'draft' CONSTRAINT entries_status_check
                                CHECK (status IN ('draft', 'approved')),
    reverses_id     bigint      CONSTRAINT entries_reverses_id_fkey REFERENCES finance.entries (id),
    reversed_by_id  bigint      CONSTRAINT entries_reversed_by_id_fkey REFERENCES finance.entries (id),
    reason          text,
    created_by      bigint,                               -- none: made by the system
    created_at      timestamptz NOT NULL DEFAULT now(),
    approved_by     bigint,
    approved_at     timestamptz,
    CONSTRAINT entries_reversal_check CHECK ((source_kind = 'reversal') = (reverses_id IS NOT NULL)),
    CONSTRAINT entries_source_check CHECK (source_kind = 'reversal' OR source_id IS NOT NULL),
    CONSTRAINT entries_reason_check CHECK (source_kind <> 'reversal' OR reason IS NOT NULL),
    CONSTRAINT entries_approved_check CHECK ((status = 'approved') = (approved_at IS NOT NULL)),
    CONSTRAINT entries_reversed_check CHECK (reversed_by_id IS NULL OR status = 'approved')
);
-- one live entry per document; a reversed one frees it for a new entry
CREATE UNIQUE INDEX entries_one_per_source ON finance.entries (source_kind, source_id)
    WHERE source_kind <> 'reversal' AND reversed_by_id IS NULL;
CREATE UNIQUE INDEX entries_one_reversal ON finance.entries (reverses_id) WHERE reverses_id IS NOT NULL;
CREATE INDEX entries_entry_date_idx ON finance.entries (entry_date, id);

CREATE TABLE finance.entry_lines (
    entry_id    bigint        NOT NULL CONSTRAINT entry_lines_entry_id_fkey REFERENCES finance.entries (id)
                              ON DELETE CASCADE,
    line_no     smallint      NOT NULL,
    account_id  bigint        NOT NULL CONSTRAINT entry_lines_account_id_fkey REFERENCES finance.accounts (id),
    debit       numeric(12,3) NOT NULL DEFAULT 0,
    credit      numeric(12,3) NOT NULL DEFAULT 0,
    memo        text,
    CONSTRAINT entry_lines_pkey PRIMARY KEY (entry_id, line_no),
    CONSTRAINT entry_lines_amount_check CHECK (debit >= 0 AND credit >= 0 AND (debit = 0) <> (credit = 0))
);
CREATE INDEX entry_lines_account_id_idx ON finance.entry_lines (account_id);

-- Lines are written while their entry is a draft, never changed, and removed only with a draft.
CREATE FUNCTION finance.guard_lines() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    s text;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'entry lines are immutable';
    END IF;
    SELECT status INTO s FROM finance.entries WHERE id = CASE WHEN TG_OP = 'DELETE' THEN OLD.entry_id ELSE NEW.entry_id END;
    IF s IS NOT NULL AND s <> 'draft' THEN
        RAISE EXCEPTION 'the lines of an approved entry cannot change';
    END IF;
    RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END $$;
CREATE TRIGGER lines_guard BEFORE INSERT OR UPDATE OR DELETE ON finance.entry_lines
    FOR EACH ROW EXECUTE FUNCTION finance.guard_lines();

CREATE FUNCTION finance.check_balanced() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM finance.entries WHERE id = NEW.entry_id)
       AND (SELECT count(*) < 2 OR sum(debit) <> sum(credit) FROM finance.entry_lines WHERE entry_id = NEW.entry_id) THEN
        RAISE EXCEPTION 'entry % does not balance', NEW.entry_id;
    END IF;
    RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER lines_balanced AFTER INSERT ON finance.entry_lines
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION finance.check_balanced();

-- A draft is approved or deleted; an approved entry never changes, except to record the entry that reverses it.
CREATE FUNCTION finance.guard_entry() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    approval constant text[] := ARRAY['status', 'approved_by', 'approved_at'];
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'draft' THEN
            RAISE EXCEPTION 'an approved entry cannot be deleted: reverse it';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.status = 'draft' THEN
        IF NEW.status <> 'approved' OR (to_jsonb(NEW) - approval) <> (to_jsonb(OLD) - approval) THEN
            RAISE EXCEPTION 'a draft entry can only be approved';
        END IF;
        IF (SELECT count(*) < 2 OR sum(debit) <> sum(credit) FROM finance.entry_lines WHERE entry_id = NEW.id) THEN
            RAISE EXCEPTION 'entry % cannot be approved without balanced lines', NEW.id;
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.reversed_by_id IS NOT NULL OR NEW.reversed_by_id IS NULL
       OR (to_jsonb(NEW) - 'reversed_by_id') <> (to_jsonb(OLD) - 'reversed_by_id') THEN
        RAISE EXCEPTION 'an approved entry is never changed: reverse it';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER entry_guard BEFORE UPDATE OR DELETE ON finance.entries
    FOR EACH ROW EXECUTE FUNCTION finance.guard_entry();

-- A default chart for the accountant to replace with his own codes; the roles say which account each posting uses.
INSERT INTO finance.accounts (code, name, type) VALUES
    ('1101', '{"ar": "الخزينة", "en": "Treasury"}', 'asset'),
    ('1102', '{"ar": "البنك", "en": "Bank"}', 'asset'),
    ('1103', '{"ar": "الكاش لدى السائقين", "en": "Cash held by drivers"}', 'asset'),
    ('1104', '{"ar": "ذمم الموظفين", "en": "Employee receivables"}', 'asset'),
    ('2101', '{"ar": "مستحقات المنصات (الدفع عند الاستلام)", "en": "Due to platforms (cash on delivery)"}', 'liability'),
    ('2102', '{"ar": "الموردون ومراكز الصيانة", "en": "Suppliers and maintenance centers"}', 'liability'),
    ('2103', '{"ar": "رواتب مستحقة", "en": "Salaries payable"}', 'liability'),
    ('3101', '{"ar": "أرصدة افتتاحية", "en": "Opening balances"}', 'equity'),
    ('4101', '{"ar": "استرداد تلفيات الحوادث", "en": "Accident damage recovered"}', 'income'),
    ('4102', '{"ar": "استرداد المخالفات المرورية", "en": "Traffic fines recovered"}', 'income'),
    ('4103', '{"ar": "استردادات أخرى من الموظفين", "en": "Other recoveries from employees"}', 'income'),
    ('4104', '{"ar": "تسويات الكاش", "en": "Cash adjustments"}', 'income'),
    ('5101', '{"ar": "الرواتب والأجور", "en": "Salaries and wages"}', 'expense'),
    ('5102', '{"ar": "الصيانة والإصلاح", "en": "Maintenance and repairs"}', 'expense'),
    ('5103', '{"ar": "المخالفات المرورية", "en": "Traffic fines"}', 'expense'),
    ('5104', '{"ar": "الوقود", "en": "Fuel"}', 'expense'),
    ('5105', '{"ar": "كاش سائقين مشطوب", "en": "Driver cash written off"}', 'expense'),
    ('5106', '{"ar": "مصروفات مكتبية", "en": "Office expenses"}', 'expense'),
    ('5107', '{"ar": "مصروفات أخرى", "en": "Other expenses"}', 'expense');

INSERT INTO finance.account_roles (role, account_id)
SELECT r.role, a.id FROM (VALUES
    ('treasury', '1101'), ('bank', '1102'), ('driver_cash', '1103'), ('employee_receivable', '1104'),
    ('payroll_recovery', '1104'), ('deduction_advance', '1101'), ('cod_clearing', '2101'),
    ('suppliers_payable', '2102'), ('salaries_payable', '2103'), ('opening_equity', '3101'),
    ('deduction_accident', '4101'), ('deduction_fine', '4102'), ('deduction_sim', '4103'), ('deduction_other', '4103'),
    ('cash_adjustments', '4104'), ('salaries_expense', '5101'), ('maintenance_expense', '5102'),
    ('traffic_fines_expense', '5103'), ('cash_writeoff', '5105')
) AS r (role, code) JOIN finance.accounts a ON a.code = r.code;

INSERT INTO finance.expense_types (code, name, account_id, sort_order)
SELECT t.code, t.name::jsonb, a.id, t.sort_order FROM (VALUES
    ('fuel', '{"ar": "وقود", "en": "Fuel"}', '5104', 10),
    ('repairs', '{"ar": "صيانة خارج المراكز", "en": "Repairs outside the centers"}', '5102', 20),
    ('office', '{"ar": "مصروفات مكتبية", "en": "Office"}', '5106', 30),
    ('other', '{"ar": "أخرى", "en": "Other"}', '5107', 90)
) AS t (code, name, code_account, sort_order) JOIN finance.accounts a ON a.code = t.code_account;

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
