"""Approval workflows (BRD FR-WFL-01..05): for a process (expenses, payroll runs, maintenance quotes...), the steps a
document goes through before it is approved, each by a role or a person, from an amount; a reason for every refusal;
every decision kept; delegation while away and escalation after a time.

A process without a workflow keeps the one approval it has today, by permission. A document's request copies the steps
that apply to its amount when it starts, so changing the workflow never changes a request already under way; a document
whose amount changes starts over. One person approves one step of a request at most.

Revision ID: 0022_approvals
Revises: 0021_finance
"""

from alembic import op

revision = "0022_approvals"
down_revision = "0021_finance"
branch_labels = None
depends_on = None

SQL = r"""
CREATE SCHEMA approvals;

CREATE TABLE approvals.workflows (
    process     text        CONSTRAINT workflows_pkey PRIMARY KEY
                            CONSTRAINT workflows_process_check
                            CHECK (process IN ('daily_report', 'maintenance_request', 'maintenance_quote',
                                               'maintenance_invoice', 'accident_estimate', 'expense', 'payroll_run')),
    active      boolean     NOT NULL DEFAULT true,
    updated_by  bigint,
    updated_at  timestamptz NOT NULL DEFAULT now(),
    version     integer     NOT NULL DEFAULT 1
);

CREATE TABLE approvals.steps (
    process               text          NOT NULL CONSTRAINT steps_process_fkey
                                        REFERENCES approvals.workflows (process) ON DELETE CASCADE,
    position              smallint      NOT NULL,
    name                  jsonb         NOT NULL,
    role_id               bigint        CONSTRAINT steps_role_id_fkey REFERENCES identity.roles (id),
    user_id               bigint        CONSTRAINT steps_user_id_fkey REFERENCES identity.users (id),
    min_amount            numeric(12,3) NOT NULL DEFAULT 0 CONSTRAINT steps_min_amount_check CHECK (min_amount >= 0),
    escalate_after_hours  integer       CONSTRAINT steps_escalate_after_hours_check CHECK (escalate_after_hours > 0),
    escalate_role_id      bigint        CONSTRAINT steps_escalate_role_id_fkey REFERENCES identity.roles (id),
    CONSTRAINT steps_pkey PRIMARY KEY (process, position),
    CONSTRAINT steps_approver_check CHECK ((role_id IS NULL) <> (user_id IS NULL)),
    CONSTRAINT steps_escalation_check CHECK ((escalate_after_hours IS NULL) = (escalate_role_id IS NULL))
);

CREATE TABLE approvals.requests (
    id            bigint        GENERATED BY DEFAULT AS IDENTITY CONSTRAINT requests_pkey PRIMARY KEY,
    public_id     uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT requests_public_id_key UNIQUE,
    process       text          NOT NULL,
    document_id   bigint        NOT NULL,
    document_key  text          NOT NULL,                   -- the document's public id, for the screens
    document_ref  text          NOT NULL,                   -- what people call it ("#12", "INV-7")
    company_id    bigint,
    amount        numeric(12,3) NOT NULL DEFAULT 0,
    steps         jsonb         NOT NULL,                   -- the steps that applied when it started, in order
    current       smallint      NOT NULL DEFAULT 0,         -- the next step to decide
    step_since    timestamptz   NOT NULL DEFAULT now(),     -- when that step began: the escalation clock
    escalated     boolean       NOT NULL DEFAULT false,
    status        text          NOT NULL DEFAULT 'pending' CONSTRAINT requests_status_check
                                CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),
    created_by    bigint,
    created_at    timestamptz   NOT NULL DEFAULT now(),
    closed_at     timestamptz,
    cancel_note   text,                                     -- why it was cancelled: withdrawn, amount_changed...
    CONSTRAINT requests_closed_check CHECK ((status = 'pending') = (closed_at IS NULL))
);
-- one request under way per document; a refused one may be followed by another (the document sent again). Cancelled:
-- the document was withdrawn, its amount changed, or the workflow was switched off before the last step
CREATE UNIQUE INDEX requests_one_pending ON approvals.requests (process, document_id) WHERE status = 'pending';
CREATE INDEX requests_document_idx ON approvals.requests (process, document_key, id);
CREATE INDEX requests_status_idx ON approvals.requests (status, step_since);

CREATE TABLE approvals.decisions (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY CONSTRAINT decisions_pkey PRIMARY KEY,
    request_id    bigint      NOT NULL CONSTRAINT decisions_request_id_fkey REFERENCES approvals.requests (id),
    step          smallint    NOT NULL,
    decision      text        NOT NULL CONSTRAINT decisions_decision_check
                              CHECK (decision IN ('approved', 'rejected', 'escalated')),
    user_id       bigint,                                   -- none: the system escalated it
    on_behalf_of  bigint,                                   -- the approver whose delegate decided
    reason        text,
    at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT decisions_reason_check CHECK (decision <> 'rejected' OR reason IS NOT NULL)
);
CREATE INDEX decisions_request_id_idx ON approvals.decisions (request_id, id);

CREATE TABLE approvals.delegations (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY CONSTRAINT delegations_pkey PRIMARY KEY,
    public_id     uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT delegations_public_id_key UNIQUE,
    user_id       bigint      NOT NULL CONSTRAINT delegations_user_id_fkey REFERENCES identity.users (id),
    delegate_id   bigint      NOT NULL CONSTRAINT delegations_delegate_id_fkey REFERENCES identity.users (id),
    date_from     date        NOT NULL,
    date_to       date        NOT NULL,
    reason        text,
    created_by    bigint      NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    cancelled_at  timestamptz,
    CONSTRAINT delegations_self_check CHECK (user_id <> delegate_id),
    CONSTRAINT delegations_range_check CHECK (date_to >= date_from)
);
CREATE INDEX delegations_delegate_id_idx ON approvals.delegations (delegate_id, date_from);

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
