"""What the driver is told in the app (BRD FR-NTF-01/02, FR-CSH-04, FR-MNT-10): a receipt issued, a report refused or
its cash corrected, a maintenance request decided or the vehicle ready, an accident's outcome, a fine or a deduction
charged, a payslip ready, a document about to expire. Read in the app's notifications screen; pushed to the phone
once push is set up (pushed_at).

Revision ID: 0024_driver_notices
Revises: 0023_chart_of_accounts
"""

from alembic import op

revision = "0024_driver_notices"
down_revision = "0023_chart_of_accounts"
branch_labels = None
depends_on = None

SQL = r"""
CREATE TABLE notifications.driver_notices (
    id           bigint      GENERATED BY DEFAULT AS IDENTITY CONSTRAINT driver_notices_pkey PRIMARY KEY,
    public_id    uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT driver_notices_public_id_key UNIQUE,
    employee_id  bigint      NOT NULL CONSTRAINT driver_notices_employee_id_fkey REFERENCES people.employees (id),
    kind         text        NOT NULL,
    params       jsonb       NOT NULL DEFAULT '{}',
    entity_type  text,
    entity_id    text,
    dedupe_key   text,                                -- one notice per situation (a document's expiry date)
    created_at   timestamptz NOT NULL DEFAULT now(),
    read_at      timestamptz,
    pushed_at    timestamptz
);
CREATE INDEX driver_notices_employee_id_idx ON notifications.driver_notices (employee_id, id);
CREATE UNIQUE INDEX driver_notices_dedupe_idx ON notifications.driver_notices (employee_id, dedupe_key)
    WHERE dedupe_key IS NOT NULL;
CREATE INDEX driver_notices_unpushed_idx ON notifications.driver_notices (id) WHERE pushed_at IS NULL;

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
