"""Editing the daily report (BRD FR-DWR-04, FR-DWR-06, BR-06): the reviewer may send a report back to the driver
with the reason (returned), the driver corrects it until it is approved; after approval a change is asked for and
approved. Every change is kept with what it was and what it became.

Revision ID: 0027_report_changes
Revises: 0026_report_escalations
"""

from alembic import op

revision = "0027_report_changes"
down_revision = "0026_report_escalations"
branch_labels = None
depends_on = None

SQL = r"""
ALTER TABLE daily_ops.reports DROP CONSTRAINT reports_status_check;
ALTER TABLE daily_ops.reports ADD CONSTRAINT reports_status_check
    CHECK (status IN ('submitted', 'returned', 'approved', 'rejected'));
ALTER TABLE daily_ops.reports ADD COLUMN updated_at timestamptz;  -- last corrected by the driver

CREATE TABLE daily_ops.report_changes (
    id                 bigint      GENERATED BY DEFAULT AS IDENTITY CONSTRAINT report_changes_pkey PRIMARY KEY,
    public_id          uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT report_changes_public_id_key UNIQUE,
    report_id          bigint      NOT NULL CONSTRAINT report_changes_report_id_fkey REFERENCES daily_ops.reports (id),
    -- edit: the driver before approval; returned: the reviewer sent it back; request: after approval, decided
    kind               text        NOT NULL CONSTRAINT report_changes_kind_check
                                   CHECK (kind IN ('edit', 'returned', 'request')),
    status             text        NOT NULL CONSTRAINT report_changes_status_check
                                   CHECK (status IN ('applied', 'pending', 'approved', 'rejected')),
    before             jsonb       NOT NULL DEFAULT '{}',
    after              jsonb       NOT NULL DEFAULT '{}',
    reason             text,
    created_at         timestamptz NOT NULL DEFAULT now(),
    created_by         bigint,      -- an office user
    created_by_device  bigint,      -- the driver's phone
    decided_by         bigint,
    decided_at         timestamptz,
    decision_note      text,
    CONSTRAINT report_changes_author_check CHECK (created_by IS NOT NULL OR created_by_device IS NOT NULL)
);
CREATE INDEX report_changes_report_id_idx ON daily_ops.report_changes (report_id, id);
CREATE UNIQUE INDEX report_changes_one_pending_idx ON daily_ops.report_changes (report_id) WHERE status = 'pending';

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
