"""What the driver asks for from the app (BRD FR-ASG-04, FR-APP-02, FR-APP-05): a change of vehicle with his reason,
for the supervisor; and a renewed document (residence, licence…) with its new expiry, which becomes his current
document only once the office has checked it.

Revision ID: 0028_driver_requests
Revises: 0027_report_changes
"""

from alembic import op

revision = "0028_driver_requests"
down_revision = "0027_report_changes"
branch_labels = None
depends_on = None

SQL = r"""
CREATE TABLE fleet.vehicle_change_requests (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY CONSTRAINT vehicle_change_requests_pkey PRIMARY KEY,
    public_id     uuid        NOT NULL DEFAULT gen_random_uuid()
                              CONSTRAINT vehicle_change_requests_public_id_key UNIQUE,
    employee_id   bigint      NOT NULL CONSTRAINT vehicle_change_requests_employee_id_fkey
                              REFERENCES people.employees (id),
    company_id    bigint      NOT NULL,
    custody_id    bigint      NOT NULL CONSTRAINT vehicle_change_requests_custody_id_fkey
                              REFERENCES fleet.custodies (id),
    vehicle_id    bigint      NOT NULL CONSTRAINT vehicle_change_requests_vehicle_id_fkey
                              REFERENCES fleet.vehicles (id),
    reason        text        NOT NULL,
    -- done: the vehicle was changed (closed by the supervisor, or by its return); rejected: with the note
    status        text        NOT NULL DEFAULT 'pending' CONSTRAINT vehicle_change_requests_status_check
                              CHECK (status IN ('pending', 'done', 'rejected')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    created_by_device bigint,
    decided_by    bigint,
    decided_at    timestamptz,
    note          text
);
CREATE UNIQUE INDEX vehicle_change_requests_one_pending_idx ON fleet.vehicle_change_requests (custody_id)
    WHERE status = 'pending';

CREATE TABLE documents.renewals (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY CONSTRAINT renewals_pkey PRIMARY KEY,
    public_id     uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT renewals_public_id_key UNIQUE,
    employee_id   bigint      NOT NULL CONSTRAINT renewals_employee_id_fkey REFERENCES people.employees (id),
    company_id    bigint      NOT NULL,
    type_code     text        NOT NULL CONSTRAINT renewals_type_code_fkey REFERENCES documents.document_types (code),
    number        text,
    expiry_date   date        NOT NULL,
    file_sha256   text        NOT NULL CONSTRAINT renewals_file_sha256_fkey REFERENCES files.files (sha256),
    status        text        NOT NULL DEFAULT 'pending' CONSTRAINT renewals_status_check
                              CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    created_by_device bigint,
    decided_by    bigint,
    decided_at    timestamptz,
    note          text,
    document_id   bigint      CONSTRAINT renewals_document_id_fkey REFERENCES documents.documents (id)
);
CREATE UNIQUE INDEX renewals_one_pending_idx ON documents.renewals (employee_id, type_code) WHERE status = 'pending';

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
