"""An office user who forgot the password asks for a one-time code on the phone saved on the account and sets a new
one with it (BRD FR-USR-03); with two-step verification on, the authenticator's code is asked too.

Revision ID: 0030_password_reset_codes
Revises: 0029_audit_device_comment
"""

from alembic import op

revision = "0030_password_reset_codes"
down_revision = "0029_audit_device_comment"
branch_labels = None
depends_on = None

SQL = r"""
CREATE TABLE identity.password_reset_codes (
    id          bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT password_reset_codes_pkey PRIMARY KEY,
    username    text NOT NULL,
    user_id     bigint CONSTRAINT password_reset_codes_user_id_fkey REFERENCES identity.users (id),
    code_hash   text,
    attempts    integer NOT NULL DEFAULT 0,
    created_at  timestamptz NOT NULL DEFAULT now(),
    expires_at  timestamptz NOT NULL,
    consumed_at timestamptz,
    ip          text
);
CREATE INDEX password_reset_codes_username_idx ON identity.password_reset_codes (username, created_at);

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
