"""Fuel (BRD FR-FUL-01..05, UAT-03): fills from the driver's app or the office, with the invoice and the odometer's
photo; the checks before approval (litres within the tank, the amount at the official price within a tolerance, a fuel
the vehicle takes, an odometer above the last reading and plausible); a flagged fill waits for the accountant, who
decides with a reason; the consumption per 100 km against a reference per make and model; official prices with the
date they apply from.

Revision ID: 0033_fuel
Revises: 0032_more_approvals
"""

from alembic import op

revision = "0033_fuel"
down_revision = "0032_more_approvals"
branch_labels = None
depends_on = None

SQL = r"""
CREATE SCHEMA fuel;

-- the official price per litre from a date (FR-FUL-05): the price of a fill is the last one from on or before its day
CREATE TABLE fuel.prices (
    id              bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT prices_pkey PRIMARY KEY,
    fuel_type       text          NOT NULL CONSTRAINT prices_fuel_type_check
                                  CHECK (fuel_type IN ('premium_91', 'super_95', 'ultra_98', 'diesel')),
    price           numeric(8,3)  NOT NULL CONSTRAINT prices_price_check CHECK (price > 0),
    effective_from  date          NOT NULL,
    created_by      bigint        NOT NULL,
    created_at      timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT prices_fuel_type_effective_from_key UNIQUE (fuel_type, effective_from)
);

-- what a make and model takes, holds and burns (FR-FUL-02, FR-FUL-04)
CREATE TABLE fuel.models (
    id                bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT models_pkey PRIMARY KEY,
    make              text          NOT NULL,
    model             text          NOT NULL,
    tank_litres       numeric(6,1)  NOT NULL CONSTRAINT models_tank_litres_check CHECK (tank_litres > 0),
    fuel_types        text[]        NOT NULL CONSTRAINT models_fuel_types_check
                                    CHECK (cardinality(fuel_types) > 0
                                           AND fuel_types <@ ARRAY['premium_91', 'super_95', 'ultra_98', 'diesel']),
    litres_per_100km  numeric(5,2)  NOT NULL CONSTRAINT models_litres_per_100km_check CHECK (litres_per_100km > 0),
    updated_by        bigint        NOT NULL,
    updated_at        timestamptz   NOT NULL DEFAULT now(),
    version           integer       NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX models_make_model_idx ON fuel.models (lower(make), lower(model));

CREATE SEQUENCE fuel.fill_number_seq;
CREATE TABLE fuel.fills (
    id                bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT fills_pkey PRIMARY KEY,
    public_id         uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT fills_public_id_key UNIQUE,
    number            integer       NOT NULL DEFAULT nextval('fuel.fill_number_seq') CONSTRAINT fills_number_key UNIQUE,
    company_id        bigint        NOT NULL CONSTRAINT fills_company_id_fkey REFERENCES org.companies (id),
    vehicle_id        bigint        NOT NULL CONSTRAINT fills_vehicle_id_fkey REFERENCES fleet.vehicles (id),
    custody_id        bigint        CONSTRAINT fills_custody_id_fkey REFERENCES fleet.custodies (id),
    driver_id         bigint        CONSTRAINT fills_driver_id_fkey REFERENCES people.employees (id),
    filled_at         timestamptz   NOT NULL,
    business_date     date          NOT NULL,
    litres            numeric(7,2)  NOT NULL CONSTRAINT fills_litres_check CHECK (litres > 0),
    amount            numeric(10,3) NOT NULL CONSTRAINT fills_amount_check CHECK (amount > 0),
    fuel_type         text          NOT NULL CONSTRAINT fills_fuel_type_check
                                    CHECK (fuel_type IN ('premium_91', 'super_95', 'ultra_98', 'diesel')),
    station           text,
    odometer_km       integer       NOT NULL CONSTRAINT fills_odometer_km_check CHECK (odometer_km >= 0),
    invoice_sha256    text          NOT NULL CONSTRAINT fills_invoice_sha256_fkey REFERENCES files.files (sha256),
    odometer_sha256   text          CONSTRAINT fills_odometer_sha256_fkey REFERENCES files.files (sha256),
    source            text          NOT NULL CONSTRAINT fills_source_check CHECK (source IN ('app', 'office')),
    price             numeric(8,3),                 -- the official price that applied, if any was set
    expected_amount   numeric(10,3),                -- litres x that price
    flags             text[]        NOT NULL DEFAULT '{}',
    km_since          integer,                      -- from the vehicle's previous approved fill
    litres_per_100km  numeric(6,2),                 -- this fill's litres over those kilometers
    status            text          NOT NULL DEFAULT 'pending' CONSTRAINT fills_status_check
                                    CHECK (status IN ('pending', 'approved', 'rejected')),
    decided_by        bigint,                       -- none: approved by the checks alone
    decided_at        timestamptz,
    decision_note     text,
    expense_id        bigint        CONSTRAINT fills_expense_id_fkey REFERENCES finance.expenses (id),
    created_by_user   bigint,
    created_by_device bigint,
    created_at        timestamptz   NOT NULL DEFAULT now(),
    -- a flagged fill is approved only by a person, with the reason (FR-FUL-03); a refusal always has its reason
    CONSTRAINT fills_flagged_check
        CHECK (status <> 'approved' OR cardinality(flags) = 0 OR (decided_by IS NOT NULL AND decision_note IS NOT NULL)),
    CONSTRAINT fills_rejected_check CHECK (status <> 'rejected' OR (decided_by IS NOT NULL AND decision_note IS NOT NULL)),
    CONSTRAINT fills_decided_check CHECK ((status = 'pending') = (decided_at IS NULL)),
    CONSTRAINT fills_author_check CHECK ((created_by_user IS NULL) <> (created_by_device IS NULL))
);
-- one invoice, one fill: a photo sent twice (the phone's retry, or the same invoice claimed again) is refused
CREATE UNIQUE INDEX fills_invoice_sha256_idx ON fuel.fills (invoice_sha256) WHERE status <> 'rejected';
CREATE INDEX fills_vehicle_id_idx ON fuel.fills (vehicle_id, filled_at);
CREATE INDEX fills_status_idx ON fuel.fills (status, filled_at);
CREATE INDEX fills_driver_id_idx ON fuel.fills (driver_id, filled_at);

-- a fuel expense made from a fill the checks approved has no person behind it: none means the system
ALTER TABLE finance.expenses ALTER COLUMN created_by DROP NOT NULL;

CREATE OR REPLACE FUNCTION public.fleet_apply_grants() RETURNS void LANGUAGE plpgsql AS $$
DECLARE
    s text;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'fleet_app') THEN
        RETURN;
    END IF;
    FOR s IN SELECT nspname FROM pg_namespace
             WHERE nspname = ANY (ARRAY['org', 'identity', 'audit', 'integrations', 'i18n', 'files', 'people',
                                        'documents', 'fleet', 'tracking', 'onboarding', 'daily_ops', 'cash',
                                        'maintenance', 'accidents', 'fines', 'payroll', 'attendance', 'finance',
                                        'approvals', 'notifications', 'reports', 'fuel', 'violations'])
    LOOP
        EXECUTE format('GRANT USAGE ON SCHEMA %I TO fleet_app', s);
        EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO fleet_app', s);
        IF s = 'audit' THEN
            EXECUTE 'GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA audit TO fleet_app';
        ELSE
            EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO fleet_app', s);
        END IF;
    END LOOP;
    IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'tracking') THEN
        EXECUTE 'GRANT EXECUTE ON FUNCTION tracking.ensure_month_partition(date), '
                'tracking.drop_partitions_before(date) TO fleet_app';
    END IF;
    EXECUTE 'ALTER ROLE fleet_app SET statement_timeout = ''30s''';
END $$;

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
