"""Work violations (BRD FR-VIO-01..05, BR-09, BR-10, BR-13, UAT-05; TRK-M-02/03): a violation of a driver from one
of six sources (attendance, cash, orders, complaints, accidents, tracking), recorded by the office, converted from an
alert by a supervisor, or opened by the system itself (a fake location; signal lost three times in a week). It waits
for review, is approved (with a penalty or as a warning) or excluded; the driver may object from the app within the
deadline; the objection is decided finally. A cause outside the driver's responsibility from a list the client keeps
(customer cancelled, wrong address from the platform, restaurant late) excludes it at once. A penalty becomes a payroll
deduction only once final.

Revision ID: 0034_violations
Revises: 0033_fuel
"""

from alembic import op

revision = "0034_violations"
down_revision = "0033_fuel"
branch_labels = None
depends_on = None

SQL = r"""
CREATE SCHEMA violations;

CREATE TABLE violations.types (
    id          bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT types_pkey PRIMARY KEY,
    code        text          NOT NULL CONSTRAINT types_code_key UNIQUE,
    name        jsonb         NOT NULL,
    source      text          NOT NULL CONSTRAINT types_source_check
                              CHECK (source IN ('attendance', 'cash', 'orders', 'complaints', 'accidents', 'tracking')),
    amount      numeric(10,3) CONSTRAINT types_amount_check CHECK (amount >= 0),
    active      boolean       NOT NULL DEFAULT true,
    version     integer       NOT NULL DEFAULT 1
);

-- causes outside the driver's responsibility (BR-10): a violation recorded with an active one is excluded at once
CREATE TABLE violations.causes (
    id          bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT causes_pkey PRIMARY KEY,
    code        text          NOT NULL CONSTRAINT causes_code_key UNIQUE,
    name        jsonb         NOT NULL,
    active      boolean       NOT NULL DEFAULT true,
    version     integer       NOT NULL DEFAULT 1
);

CREATE SEQUENCE violations.violation_number_seq;
CREATE TABLE violations.violations (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT violations_pkey PRIMARY KEY,
    public_id           uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT violations_public_id_key UNIQUE,
    number              integer       NOT NULL DEFAULT nextval('violations.violation_number_seq')
                                      CONSTRAINT violations_number_key UNIQUE,
    company_id          bigint        NOT NULL CONSTRAINT violations_company_id_fkey REFERENCES org.companies (id),
    employee_id         bigint        NOT NULL CONSTRAINT violations_employee_id_fkey REFERENCES people.employees (id),
    type_id             bigint        NOT NULL CONSTRAINT violations_type_id_fkey REFERENCES violations.types (id),
    cause_id            bigint        CONSTRAINT violations_cause_id_fkey REFERENCES violations.causes (id),
    vehicle_id          bigint        CONSTRAINT violations_vehicle_id_fkey REFERENCES fleet.vehicles (id),
    occurred_at         timestamptz   NOT NULL,
    business_date       date          NOT NULL,
    description         text          NOT NULL,
    reference           text,
    evidence_sha256     text          CONSTRAINT violations_evidence_sha256_fkey REFERENCES files.files (sha256),
    origin              text          NOT NULL CONSTRAINT violations_origin_check
                                      CHECK (origin IN ('office', 'alert', 'system')),
    alert_id            bigint,
    auto_key            text,
    status              text          NOT NULL DEFAULT 'pending' CONSTRAINT violations_status_check
                                      CHECK (status IN ('pending', 'approved', 'excluded', 'objected', 'upheld',
                                                        'overturned')),
    amount              numeric(10,3) CONSTRAINT violations_amount_check CHECK (amount >= 0),
    review_note         text,
    reviewed_by         bigint,
    reviewed_at         timestamptz,
    objection_deadline  timestamptz,
    objection           text,
    objection_sha256    text          CONSTRAINT violations_objection_sha256_fkey REFERENCES files.files (sha256),
    objected_at         timestamptz,
    final_note          text,
    final_by            bigint,
    final_at            timestamptz,
    deduction_id        bigint,
    created_by          bigint,
    created_at          timestamptz   NOT NULL DEFAULT now(),
    version             integer       NOT NULL DEFAULT 1,
    CONSTRAINT violations_reviewed_check CHECK (status = 'pending' OR reviewed_at IS NOT NULL),
    CONSTRAINT violations_objected_check CHECK (status NOT IN ('objected', 'upheld', 'overturned')
                                                OR objected_at IS NOT NULL),
    CONSTRAINT violations_final_check CHECK (status NOT IN ('upheld', 'overturned') OR final_at IS NOT NULL)
);
CREATE UNIQUE INDEX violations_auto_key_idx ON violations.violations (auto_key) WHERE auto_key IS NOT NULL;
CREATE INDEX violations_employee_id_idx ON violations.violations (employee_id, occurred_at DESC);
CREATE INDEX violations_status_idx ON violations.violations (status) WHERE status IN ('pending', 'objected');
CREATE INDEX violations_due_idx ON violations.violations (objection_deadline)
    WHERE status = 'approved' AND deduction_id IS NULL;

-- the signal losses of each driver (TRK-M-03): the third in a week opens a violation for review
CREATE TABLE violations.signal_losses (
    id           bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT signal_losses_pkey PRIMARY KEY,
    employee_id  bigint       NOT NULL CONSTRAINT signal_losses_employee_id_fkey REFERENCES people.employees (id),
    lost_at      timestamptz  NOT NULL,
    custody_id   bigint       NOT NULL,
    CONSTRAINT signal_losses_custody_id_lost_at_key UNIQUE (custody_id, lost_at)
);
CREATE INDEX signal_losses_employee_id_idx ON violations.signal_losses (employee_id, lost_at);

INSERT INTO violations.types (code, name, source) VALUES
    ('late_start',        '{"ar": "تأخر عن بدء الدوام", "en": "Late start"}', 'attendance'),
    ('absence',           '{"ar": "غياب دون إذن", "en": "Absence without leave"}', 'attendance'),
    ('report_late',       '{"ar": "تأخر التقرير اليومي", "en": "Daily report late"}', 'attendance'),
    ('cash_deposit_late', '{"ar": "تأخر إيداع الكاش", "en": "Cash deposited late"}', 'cash'),
    ('cash_shortage',     '{"ar": "عجز في الكاش", "en": "Cash shortage"}', 'cash'),
    ('order_rejected',    '{"ar": "رفض طلب", "en": "Order rejected"}', 'orders'),
    ('order_late',        '{"ar": "تأخر توصيل طلب", "en": "Late delivery"}', 'orders'),
    ('order_cancelled',   '{"ar": "طلب ملغى بسبب السائق", "en": "Order cancelled by the driver"}', 'orders'),
    ('complaint',         '{"ar": "شكوى عميل", "en": "Customer complaint"}', 'complaints'),
    ('reckless_driving',  '{"ar": "قيادة متهورة", "en": "Reckless driving"}', 'accidents'),
    ('mock_location',     '{"ar": "تزييف الموقع", "en": "Fake location"}', 'tracking'),
    ('signal_loss',       '{"ar": "انقطاع الإشارة المتكرر", "en": "Repeated signal loss"}', 'tracking'),
    ('speeding',          '{"ar": "تجاوز السرعة", "en": "Speeding"}', 'tracking');

INSERT INTO violations.causes (code, name) VALUES
    ('customer_cancelled', '{"ar": "إلغاء من العميل", "en": "Cancelled by the customer"}'),
    ('wrong_address',      '{"ar": "عنوان خاطئ من المنصة", "en": "Wrong address from the platform"}'),
    ('restaurant_delay',   '{"ar": "تأخر المطعم", "en": "Restaurant delay"}');

-- a final violation's penalty is a payroll deduction like a fine's
ALTER TABLE payroll.deductions DROP CONSTRAINT deductions_source_type_check;
ALTER TABLE payroll.deductions ADD CONSTRAINT deductions_source_type_check
    CHECK (source_type IN ('accident', 'fine', 'violation', 'advance', 'sim', 'other'));

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.get_bind().connection.driver_connection.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
