"""The branch treasury's daily count and close: the accountant counts the cash in the drawer at the end of a day and
enters it (optionally by note and coin); the treasury's posted balance at the end of that day is kept with the count,
and a difference is posted as a cash journal of kind "count_diff" (treasury +/-X, adjustments -/+X, dated that day),
entered in the books on the cash differences account. A closed day takes no more treasury movements: a posted journal
on a branch's treasury dated on or before the branch's last closed day is refused here as well as in the service.
Only the branch's last closing may be reopened (its difference journal reversed on the same day).

Revision ID: 0038_treasury_closings
Revises: 0037_treasury
"""

from alembic import op

revision = "0038_treasury_closings"
down_revision = "0037_treasury"
branch_labels = None
depends_on = None

SQL = r"""
ALTER TABLE cash.journals DROP CONSTRAINT journals_kind_check;
ALTER TABLE cash.journals ADD CONSTRAINT journals_kind_check
    CHECK (kind IN ('collection', 'adjustment', 'deposit', 'bank_deposit', 'settlement', 'writeoff', 'reversal',
                    'opening', 'fuel', 'disbursement', 'bank_withdrawal', 'count_diff'));
ALTER TABLE cash.journals DROP CONSTRAINT journals_reason_check;
ALTER TABLE cash.journals ADD CONSTRAINT journals_reason_check
    CHECK (kind NOT IN ('adjustment', 'reversal', 'writeoff', 'count_diff') OR reason IS NOT NULL);

-- one difference journal per closing
DROP INDEX cash.journals_one_per_source;
CREATE UNIQUE INDEX journals_one_per_source ON cash.journals (source_type, source_id, kind)
    WHERE status <> 'rejected' AND kind IN ('collection', 'deposit', 'settlement', 'opening', 'disbursement',
                                            'count_diff');

CREATE TABLE cash.treasury_closings (
    id             bigint        GENERATED BY DEFAULT AS IDENTITY CONSTRAINT treasury_closings_pkey PRIMARY KEY,
    public_id      uuid          NOT NULL DEFAULT gen_random_uuid() CONSTRAINT treasury_closings_public_id_key UNIQUE,
    branch_id      bigint        NOT NULL CONSTRAINT treasury_closings_branch_id_fkey REFERENCES org.branches (id),
    day            date          NOT NULL,                  -- a Kuwait day
    book_balance   numeric(12,3) NOT NULL,                  -- the treasury's posted balance at the end of the day
    counted        numeric(12,3) NOT NULL CONSTRAINT treasury_closings_counted_check CHECK (counted >= 0),
    denominations  jsonb,                                   -- {"20": count, ..., "0.005": count}: they sum to counted
    difference     numeric(12,3) NOT NULL,
    note           text,
    journal_id     bigint        CONSTRAINT treasury_closings_journal_id_fkey REFERENCES cash.journals (id),
    closed_by      bigint        NOT NULL CONSTRAINT treasury_closings_closed_by_fkey REFERENCES identity.users (id),
    closed_at      timestamptz   NOT NULL DEFAULT now(),
    reopened_by    bigint        CONSTRAINT treasury_closings_reopened_by_fkey REFERENCES identity.users (id),
    reopened_at    timestamptz,
    reopen_reason  text,
    CONSTRAINT treasury_closings_difference_check CHECK (difference = counted - book_balance),
    CONSTRAINT treasury_closings_note_check CHECK (difference = 0 OR note IS NOT NULL),
    CONSTRAINT treasury_closings_journal_check CHECK ((difference = 0) = (journal_id IS NULL)),
    CONSTRAINT treasury_closings_reopened_check
        CHECK ((reopened_at IS NULL) = (reopened_by IS NULL) AND (reopened_at IS NULL) = (reopen_reason IS NULL))
);
-- one standing closing per branch and day; a reopened one stays as history
CREATE UNIQUE INDEX treasury_closings_active ON cash.treasury_closings (branch_id, day) WHERE reopened_at IS NULL;
CREATE INDEX treasury_closings_branch_id_idx ON cash.treasury_closings (branch_id, day);

-- A closing is never deleted nor changed, except to be reopened once.
CREATE FUNCTION cash.guard_closing() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    reopening constant text[] := ARRAY['reopened_by', 'reopened_at', 'reopen_reason'];
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'a treasury closing is never deleted: reopen it';
    END IF;
    IF OLD.reopened_at IS NOT NULL OR NEW.reopened_at IS NULL
       OR (to_jsonb(NEW) - reopening) <> (to_jsonb(OLD) - reopening) THEN
        RAISE EXCEPTION 'a treasury closing only changes when it is reopened, once';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER closing_guard BEFORE UPDATE OR DELETE ON cash.treasury_closings
    FOR EACH ROW EXECUTE FUNCTION cash.guard_closing();

-- A journal posted on a branch's treasury may not be dated on or before that branch's last closed day.
CREATE FUNCTION cash.guard_closed_day() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    closed date;
BEGIN
    IF NEW.status = 'posted' AND OLD.status <> 'posted' THEN
        SELECT max(c.day) INTO closed
        FROM cash.journal_lines l
        JOIN cash.accounts a ON a.id = l.account_id AND a.kind = 'treasury'
        JOIN cash.treasury_closings c ON c.branch_id = a.branch_id AND c.reopened_at IS NULL
        WHERE l.journal_id = NEW.id;
        IF closed IS NOT NULL AND NEW.business_date <= closed THEN
            RAISE EXCEPTION 'treasury day % is closed', NEW.business_date;
        END IF;
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER journal_closed_day BEFORE UPDATE OF status ON cash.journals
    FOR EACH ROW EXECUTE FUNCTION cash.guard_closed_day();

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
