"""A driver without a car registers one from the app; it waits for the office, and approved it becomes his custody.

Revision ID: 0043_vehicle_claims
Revises: 0042_vehicle_change_plate
"""

from alembic import op

revision = "0043_vehicle_claims"
down_revision = "0042_vehicle_change_plate"
branch_labels = None
depends_on = None

SQL = r"""
CREATE TABLE fleet.vehicle_claims (
    id            bigint      GENERATED BY DEFAULT AS IDENTITY CONSTRAINT vehicle_claims_pkey PRIMARY KEY,
    public_id     uuid        NOT NULL DEFAULT gen_random_uuid() CONSTRAINT vehicle_claims_public_id_key UNIQUE,
    employee_id   bigint      NOT NULL CONSTRAINT vehicle_claims_employee_id_fkey REFERENCES people.employees (id),
    company_id    bigint      NOT NULL,
    vehicle_id    bigint      NOT NULL CONSTRAINT vehicle_claims_vehicle_id_fkey REFERENCES fleet.vehicles (id),
    odometer_km   integer     NOT NULL CONSTRAINT vehicle_claims_odometer_km_check CHECK (odometer_km >= 0),
    photo_sha256  text        NOT NULL CONSTRAINT vehicle_claims_photo_sha256_fkey REFERENCES files.files (sha256),
    -- condition photos [{position, sha256}], kept for the custody's handover photos
    photos        jsonb       NOT NULL DEFAULT '[]'::jsonb,
    claimed_at    timestamptz NOT NULL,
    status        text        NOT NULL DEFAULT 'pending' CONSTRAINT vehicle_claims_status_check
                              CHECK (status IN ('pending', 'approved', 'rejected')),
    note          text,
    decided_by    bigint,
    decided_at    timestamptz,
    custody_id    bigint      CONSTRAINT vehicle_claims_custody_id_fkey REFERENCES fleet.custodies (id),
    client_ref    uuid        NOT NULL CONSTRAINT vehicle_claims_client_ref_key UNIQUE,
    created_by_device bigint,
    created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX vehicle_claims_one_pending_idx ON fleet.vehicle_claims (employee_id) WHERE status = 'pending';

SELECT public.fleet_apply_grants();
"""


def upgrade() -> None:
    op.execute(SQL)


def downgrade() -> None:
    raise NotImplementedError("forward-only migrations")
